// Code generated by ent, DO NOT EDIT.

package decisionaudit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldID, id))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldTimestamp, v))
}

// PrincipalKind applies equality check predicate on the "principal_kind" field. It's identical to PrincipalKindEQ.
func PrincipalKind(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldPrincipalKind, v))
}

// PrincipalID applies equality check predicate on the "principal_id" field. It's identical to PrincipalIDEQ.
func PrincipalID(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldPrincipalID, v))
}

// CredentialID applies equality check predicate on the "credential_id" field. It's identical to CredentialIDEQ.
func CredentialID(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldCredentialID, v))
}

// CredentialType applies equality check predicate on the "credential_type" field. It's identical to CredentialTypeEQ.
func CredentialType(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldCredentialType, v))
}

// Route applies equality check predicate on the "route" field. It's identical to RouteEQ.
func Route(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldRoute, v))
}

// ResourceType applies equality check predicate on the "resource_type" field. It's identical to ResourceTypeEQ.
func ResourceType(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldResourceType, v))
}

// ResourceID applies equality check predicate on the "resource_id" field. It's identical to ResourceIDEQ.
func ResourceID(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldResourceID, v))
}

// Permission applies equality check predicate on the "permission" field. It's identical to PermissionEQ.
func Permission(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldPermission, v))
}

// Result applies equality check predicate on the "result" field. It's identical to ResultEQ.
func Result(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldResult, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldReason, v))
}

// MatchedPolicy applies equality check predicate on the "matched_policy" field. It's identical to MatchedPolicyEQ.
func MatchedPolicy(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldMatchedPolicy, v))
}

// MatchedGrant applies equality check predicate on the "matched_grant" field. It's identical to MatchedGrantEQ.
func MatchedGrant(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldMatchedGrant, v))
}

// PolicyID applies equality check predicate on the "policy_id" field. It's identical to PolicyIDEQ.
func PolicyID(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldPolicyID, v))
}

// CorrelationID applies equality check predicate on the "correlation_id" field. It's identical to CorrelationIDEQ.
func CorrelationID(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldCorrelationID, v))
}

// Sampled applies equality check predicate on the "sampled" field. It's identical to SampledEQ.
func Sampled(v bool) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldSampled, v))
}

// PermissionID applies equality check predicate on the "permission_id" field. It's identical to PermissionIDEQ.
func PermissionID(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldPermissionID, v))
}

// CredentialName applies equality check predicate on the "credential_name" field. It's identical to CredentialNameEQ.
func CredentialName(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldCredentialName, v))
}

// CredentialBoundaryKind applies equality check predicate on the "credential_boundary_kind" field. It's identical to CredentialBoundaryKindEQ.
func CredentialBoundaryKind(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldCredentialBoundaryKind, v))
}

// CredentialBoundaryProjectID applies equality check predicate on the "credential_boundary_project_id" field. It's identical to CredentialBoundaryProjectIDEQ.
func CredentialBoundaryProjectID(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldCredentialBoundaryProjectID, v))
}

// CredentialLabels applies equality check predicate on the "credential_labels" field. It's identical to CredentialLabelsEQ.
func CredentialLabels(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldCredentialLabels, v))
}

// ExecutorKind applies equality check predicate on the "executor_kind" field. It's identical to ExecutorKindEQ.
func ExecutorKind(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldExecutorKind, v))
}

// ExecutorID applies equality check predicate on the "executor_id" field. It's identical to ExecutorIDEQ.
func ExecutorID(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldExecutorID, v))
}

// DeniedBy applies equality check predicate on the "denied_by" field. It's identical to DeniedByEQ.
func DeniedBy(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldDeniedBy, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldTimestamp, v))
}

// PrincipalKindEQ applies the EQ predicate on the "principal_kind" field.
func PrincipalKindEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldPrincipalKind, v))
}

// PrincipalKindNEQ applies the NEQ predicate on the "principal_kind" field.
func PrincipalKindNEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldPrincipalKind, v))
}

// PrincipalKindIn applies the In predicate on the "principal_kind" field.
func PrincipalKindIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldPrincipalKind, vs...))
}

// PrincipalKindNotIn applies the NotIn predicate on the "principal_kind" field.
func PrincipalKindNotIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldPrincipalKind, vs...))
}

// PrincipalKindGT applies the GT predicate on the "principal_kind" field.
func PrincipalKindGT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldPrincipalKind, v))
}

// PrincipalKindGTE applies the GTE predicate on the "principal_kind" field.
func PrincipalKindGTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldPrincipalKind, v))
}

// PrincipalKindLT applies the LT predicate on the "principal_kind" field.
func PrincipalKindLT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldPrincipalKind, v))
}

// PrincipalKindLTE applies the LTE predicate on the "principal_kind" field.
func PrincipalKindLTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldPrincipalKind, v))
}

// PrincipalKindContains applies the Contains predicate on the "principal_kind" field.
func PrincipalKindContains(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContains(FieldPrincipalKind, v))
}

// PrincipalKindHasPrefix applies the HasPrefix predicate on the "principal_kind" field.
func PrincipalKindHasPrefix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasPrefix(FieldPrincipalKind, v))
}

// PrincipalKindHasSuffix applies the HasSuffix predicate on the "principal_kind" field.
func PrincipalKindHasSuffix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasSuffix(FieldPrincipalKind, v))
}

// PrincipalKindEqualFold applies the EqualFold predicate on the "principal_kind" field.
func PrincipalKindEqualFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEqualFold(FieldPrincipalKind, v))
}

// PrincipalKindContainsFold applies the ContainsFold predicate on the "principal_kind" field.
func PrincipalKindContainsFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContainsFold(FieldPrincipalKind, v))
}

// PrincipalIDEQ applies the EQ predicate on the "principal_id" field.
func PrincipalIDEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldPrincipalID, v))
}

// PrincipalIDNEQ applies the NEQ predicate on the "principal_id" field.
func PrincipalIDNEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldPrincipalID, v))
}

// PrincipalIDIn applies the In predicate on the "principal_id" field.
func PrincipalIDIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldPrincipalID, vs...))
}

// PrincipalIDNotIn applies the NotIn predicate on the "principal_id" field.
func PrincipalIDNotIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldPrincipalID, vs...))
}

// PrincipalIDGT applies the GT predicate on the "principal_id" field.
func PrincipalIDGT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldPrincipalID, v))
}

// PrincipalIDGTE applies the GTE predicate on the "principal_id" field.
func PrincipalIDGTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldPrincipalID, v))
}

// PrincipalIDLT applies the LT predicate on the "principal_id" field.
func PrincipalIDLT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldPrincipalID, v))
}

// PrincipalIDLTE applies the LTE predicate on the "principal_id" field.
func PrincipalIDLTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldPrincipalID, v))
}

// PrincipalIDContains applies the Contains predicate on the "principal_id" field.
func PrincipalIDContains(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContains(FieldPrincipalID, v))
}

// PrincipalIDHasPrefix applies the HasPrefix predicate on the "principal_id" field.
func PrincipalIDHasPrefix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasPrefix(FieldPrincipalID, v))
}

// PrincipalIDHasSuffix applies the HasSuffix predicate on the "principal_id" field.
func PrincipalIDHasSuffix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasSuffix(FieldPrincipalID, v))
}

// PrincipalIDEqualFold applies the EqualFold predicate on the "principal_id" field.
func PrincipalIDEqualFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEqualFold(FieldPrincipalID, v))
}

// PrincipalIDContainsFold applies the ContainsFold predicate on the "principal_id" field.
func PrincipalIDContainsFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContainsFold(FieldPrincipalID, v))
}

// CredentialIDEQ applies the EQ predicate on the "credential_id" field.
func CredentialIDEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldCredentialID, v))
}

// CredentialIDNEQ applies the NEQ predicate on the "credential_id" field.
func CredentialIDNEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldCredentialID, v))
}

// CredentialIDIn applies the In predicate on the "credential_id" field.
func CredentialIDIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldCredentialID, vs...))
}

// CredentialIDNotIn applies the NotIn predicate on the "credential_id" field.
func CredentialIDNotIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldCredentialID, vs...))
}

// CredentialIDGT applies the GT predicate on the "credential_id" field.
func CredentialIDGT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldCredentialID, v))
}

// CredentialIDGTE applies the GTE predicate on the "credential_id" field.
func CredentialIDGTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldCredentialID, v))
}

// CredentialIDLT applies the LT predicate on the "credential_id" field.
func CredentialIDLT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldCredentialID, v))
}

// CredentialIDLTE applies the LTE predicate on the "credential_id" field.
func CredentialIDLTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldCredentialID, v))
}

// CredentialIDContains applies the Contains predicate on the "credential_id" field.
func CredentialIDContains(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContains(FieldCredentialID, v))
}

// CredentialIDHasPrefix applies the HasPrefix predicate on the "credential_id" field.
func CredentialIDHasPrefix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasPrefix(FieldCredentialID, v))
}

// CredentialIDHasSuffix applies the HasSuffix predicate on the "credential_id" field.
func CredentialIDHasSuffix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasSuffix(FieldCredentialID, v))
}

// CredentialIDIsNil applies the IsNil predicate on the "credential_id" field.
func CredentialIDIsNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIsNull(FieldCredentialID))
}

// CredentialIDNotNil applies the NotNil predicate on the "credential_id" field.
func CredentialIDNotNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotNull(FieldCredentialID))
}

// CredentialIDEqualFold applies the EqualFold predicate on the "credential_id" field.
func CredentialIDEqualFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEqualFold(FieldCredentialID, v))
}

// CredentialIDContainsFold applies the ContainsFold predicate on the "credential_id" field.
func CredentialIDContainsFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContainsFold(FieldCredentialID, v))
}

// CredentialTypeEQ applies the EQ predicate on the "credential_type" field.
func CredentialTypeEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldCredentialType, v))
}

// CredentialTypeNEQ applies the NEQ predicate on the "credential_type" field.
func CredentialTypeNEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldCredentialType, v))
}

// CredentialTypeIn applies the In predicate on the "credential_type" field.
func CredentialTypeIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldCredentialType, vs...))
}

// CredentialTypeNotIn applies the NotIn predicate on the "credential_type" field.
func CredentialTypeNotIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldCredentialType, vs...))
}

// CredentialTypeGT applies the GT predicate on the "credential_type" field.
func CredentialTypeGT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldCredentialType, v))
}

// CredentialTypeGTE applies the GTE predicate on the "credential_type" field.
func CredentialTypeGTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldCredentialType, v))
}

// CredentialTypeLT applies the LT predicate on the "credential_type" field.
func CredentialTypeLT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldCredentialType, v))
}

// CredentialTypeLTE applies the LTE predicate on the "credential_type" field.
func CredentialTypeLTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldCredentialType, v))
}

// CredentialTypeContains applies the Contains predicate on the "credential_type" field.
func CredentialTypeContains(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContains(FieldCredentialType, v))
}

// CredentialTypeHasPrefix applies the HasPrefix predicate on the "credential_type" field.
func CredentialTypeHasPrefix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasPrefix(FieldCredentialType, v))
}

// CredentialTypeHasSuffix applies the HasSuffix predicate on the "credential_type" field.
func CredentialTypeHasSuffix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasSuffix(FieldCredentialType, v))
}

// CredentialTypeIsNil applies the IsNil predicate on the "credential_type" field.
func CredentialTypeIsNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIsNull(FieldCredentialType))
}

// CredentialTypeNotNil applies the NotNil predicate on the "credential_type" field.
func CredentialTypeNotNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotNull(FieldCredentialType))
}

// CredentialTypeEqualFold applies the EqualFold predicate on the "credential_type" field.
func CredentialTypeEqualFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEqualFold(FieldCredentialType, v))
}

// CredentialTypeContainsFold applies the ContainsFold predicate on the "credential_type" field.
func CredentialTypeContainsFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContainsFold(FieldCredentialType, v))
}

// RouteEQ applies the EQ predicate on the "route" field.
func RouteEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldRoute, v))
}

// RouteNEQ applies the NEQ predicate on the "route" field.
func RouteNEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldRoute, v))
}

// RouteIn applies the In predicate on the "route" field.
func RouteIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldRoute, vs...))
}

// RouteNotIn applies the NotIn predicate on the "route" field.
func RouteNotIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldRoute, vs...))
}

// RouteGT applies the GT predicate on the "route" field.
func RouteGT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldRoute, v))
}

// RouteGTE applies the GTE predicate on the "route" field.
func RouteGTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldRoute, v))
}

// RouteLT applies the LT predicate on the "route" field.
func RouteLT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldRoute, v))
}

// RouteLTE applies the LTE predicate on the "route" field.
func RouteLTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldRoute, v))
}

// RouteContains applies the Contains predicate on the "route" field.
func RouteContains(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContains(FieldRoute, v))
}

// RouteHasPrefix applies the HasPrefix predicate on the "route" field.
func RouteHasPrefix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasPrefix(FieldRoute, v))
}

// RouteHasSuffix applies the HasSuffix predicate on the "route" field.
func RouteHasSuffix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasSuffix(FieldRoute, v))
}

// RouteIsNil applies the IsNil predicate on the "route" field.
func RouteIsNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIsNull(FieldRoute))
}

// RouteNotNil applies the NotNil predicate on the "route" field.
func RouteNotNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotNull(FieldRoute))
}

// RouteEqualFold applies the EqualFold predicate on the "route" field.
func RouteEqualFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEqualFold(FieldRoute, v))
}

// RouteContainsFold applies the ContainsFold predicate on the "route" field.
func RouteContainsFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContainsFold(FieldRoute, v))
}

// ResourceTypeEQ applies the EQ predicate on the "resource_type" field.
func ResourceTypeEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldResourceType, v))
}

// ResourceTypeNEQ applies the NEQ predicate on the "resource_type" field.
func ResourceTypeNEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldResourceType, v))
}

// ResourceTypeIn applies the In predicate on the "resource_type" field.
func ResourceTypeIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldResourceType, vs...))
}

// ResourceTypeNotIn applies the NotIn predicate on the "resource_type" field.
func ResourceTypeNotIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldResourceType, vs...))
}

// ResourceTypeGT applies the GT predicate on the "resource_type" field.
func ResourceTypeGT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldResourceType, v))
}

// ResourceTypeGTE applies the GTE predicate on the "resource_type" field.
func ResourceTypeGTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldResourceType, v))
}

// ResourceTypeLT applies the LT predicate on the "resource_type" field.
func ResourceTypeLT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldResourceType, v))
}

// ResourceTypeLTE applies the LTE predicate on the "resource_type" field.
func ResourceTypeLTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldResourceType, v))
}

// ResourceTypeContains applies the Contains predicate on the "resource_type" field.
func ResourceTypeContains(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContains(FieldResourceType, v))
}

// ResourceTypeHasPrefix applies the HasPrefix predicate on the "resource_type" field.
func ResourceTypeHasPrefix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasPrefix(FieldResourceType, v))
}

// ResourceTypeHasSuffix applies the HasSuffix predicate on the "resource_type" field.
func ResourceTypeHasSuffix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasSuffix(FieldResourceType, v))
}

// ResourceTypeEqualFold applies the EqualFold predicate on the "resource_type" field.
func ResourceTypeEqualFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEqualFold(FieldResourceType, v))
}

// ResourceTypeContainsFold applies the ContainsFold predicate on the "resource_type" field.
func ResourceTypeContainsFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContainsFold(FieldResourceType, v))
}

// ResourceIDEQ applies the EQ predicate on the "resource_id" field.
func ResourceIDEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldResourceID, v))
}

// ResourceIDNEQ applies the NEQ predicate on the "resource_id" field.
func ResourceIDNEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldResourceID, v))
}

// ResourceIDIn applies the In predicate on the "resource_id" field.
func ResourceIDIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldResourceID, vs...))
}

// ResourceIDNotIn applies the NotIn predicate on the "resource_id" field.
func ResourceIDNotIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldResourceID, vs...))
}

// ResourceIDGT applies the GT predicate on the "resource_id" field.
func ResourceIDGT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldResourceID, v))
}

// ResourceIDGTE applies the GTE predicate on the "resource_id" field.
func ResourceIDGTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldResourceID, v))
}

// ResourceIDLT applies the LT predicate on the "resource_id" field.
func ResourceIDLT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldResourceID, v))
}

// ResourceIDLTE applies the LTE predicate on the "resource_id" field.
func ResourceIDLTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldResourceID, v))
}

// ResourceIDContains applies the Contains predicate on the "resource_id" field.
func ResourceIDContains(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContains(FieldResourceID, v))
}

// ResourceIDHasPrefix applies the HasPrefix predicate on the "resource_id" field.
func ResourceIDHasPrefix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasPrefix(FieldResourceID, v))
}

// ResourceIDHasSuffix applies the HasSuffix predicate on the "resource_id" field.
func ResourceIDHasSuffix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasSuffix(FieldResourceID, v))
}

// ResourceIDIsNil applies the IsNil predicate on the "resource_id" field.
func ResourceIDIsNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIsNull(FieldResourceID))
}

// ResourceIDNotNil applies the NotNil predicate on the "resource_id" field.
func ResourceIDNotNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotNull(FieldResourceID))
}

// ResourceIDEqualFold applies the EqualFold predicate on the "resource_id" field.
func ResourceIDEqualFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEqualFold(FieldResourceID, v))
}

// ResourceIDContainsFold applies the ContainsFold predicate on the "resource_id" field.
func ResourceIDContainsFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContainsFold(FieldResourceID, v))
}

// PermissionEQ applies the EQ predicate on the "permission" field.
func PermissionEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldPermission, v))
}

// PermissionNEQ applies the NEQ predicate on the "permission" field.
func PermissionNEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldPermission, v))
}

// PermissionIn applies the In predicate on the "permission" field.
func PermissionIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldPermission, vs...))
}

// PermissionNotIn applies the NotIn predicate on the "permission" field.
func PermissionNotIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldPermission, vs...))
}

// PermissionGT applies the GT predicate on the "permission" field.
func PermissionGT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldPermission, v))
}

// PermissionGTE applies the GTE predicate on the "permission" field.
func PermissionGTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldPermission, v))
}

// PermissionLT applies the LT predicate on the "permission" field.
func PermissionLT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldPermission, v))
}

// PermissionLTE applies the LTE predicate on the "permission" field.
func PermissionLTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldPermission, v))
}

// PermissionContains applies the Contains predicate on the "permission" field.
func PermissionContains(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContains(FieldPermission, v))
}

// PermissionHasPrefix applies the HasPrefix predicate on the "permission" field.
func PermissionHasPrefix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasPrefix(FieldPermission, v))
}

// PermissionHasSuffix applies the HasSuffix predicate on the "permission" field.
func PermissionHasSuffix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasSuffix(FieldPermission, v))
}

// PermissionEqualFold applies the EqualFold predicate on the "permission" field.
func PermissionEqualFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEqualFold(FieldPermission, v))
}

// PermissionContainsFold applies the ContainsFold predicate on the "permission" field.
func PermissionContainsFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContainsFold(FieldPermission, v))
}

// ResultEQ applies the EQ predicate on the "result" field.
func ResultEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldResult, v))
}

// ResultNEQ applies the NEQ predicate on the "result" field.
func ResultNEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldResult, v))
}

// ResultIn applies the In predicate on the "result" field.
func ResultIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldResult, vs...))
}

// ResultNotIn applies the NotIn predicate on the "result" field.
func ResultNotIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldResult, vs...))
}

// ResultGT applies the GT predicate on the "result" field.
func ResultGT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldResult, v))
}

// ResultGTE applies the GTE predicate on the "result" field.
func ResultGTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldResult, v))
}

// ResultLT applies the LT predicate on the "result" field.
func ResultLT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldResult, v))
}

// ResultLTE applies the LTE predicate on the "result" field.
func ResultLTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldResult, v))
}

// ResultContains applies the Contains predicate on the "result" field.
func ResultContains(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContains(FieldResult, v))
}

// ResultHasPrefix applies the HasPrefix predicate on the "result" field.
func ResultHasPrefix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasPrefix(FieldResult, v))
}

// ResultHasSuffix applies the HasSuffix predicate on the "result" field.
func ResultHasSuffix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasSuffix(FieldResult, v))
}

// ResultEqualFold applies the EqualFold predicate on the "result" field.
func ResultEqualFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEqualFold(FieldResult, v))
}

// ResultContainsFold applies the ContainsFold predicate on the "result" field.
func ResultContainsFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContainsFold(FieldResult, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContainsFold(FieldReason, v))
}

// MatchedPolicyEQ applies the EQ predicate on the "matched_policy" field.
func MatchedPolicyEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldMatchedPolicy, v))
}

// MatchedPolicyNEQ applies the NEQ predicate on the "matched_policy" field.
func MatchedPolicyNEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldMatchedPolicy, v))
}

// MatchedPolicyIn applies the In predicate on the "matched_policy" field.
func MatchedPolicyIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldMatchedPolicy, vs...))
}

// MatchedPolicyNotIn applies the NotIn predicate on the "matched_policy" field.
func MatchedPolicyNotIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldMatchedPolicy, vs...))
}

// MatchedPolicyGT applies the GT predicate on the "matched_policy" field.
func MatchedPolicyGT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldMatchedPolicy, v))
}

// MatchedPolicyGTE applies the GTE predicate on the "matched_policy" field.
func MatchedPolicyGTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldMatchedPolicy, v))
}

// MatchedPolicyLT applies the LT predicate on the "matched_policy" field.
func MatchedPolicyLT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldMatchedPolicy, v))
}

// MatchedPolicyLTE applies the LTE predicate on the "matched_policy" field.
func MatchedPolicyLTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldMatchedPolicy, v))
}

// MatchedPolicyContains applies the Contains predicate on the "matched_policy" field.
func MatchedPolicyContains(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContains(FieldMatchedPolicy, v))
}

// MatchedPolicyHasPrefix applies the HasPrefix predicate on the "matched_policy" field.
func MatchedPolicyHasPrefix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasPrefix(FieldMatchedPolicy, v))
}

// MatchedPolicyHasSuffix applies the HasSuffix predicate on the "matched_policy" field.
func MatchedPolicyHasSuffix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasSuffix(FieldMatchedPolicy, v))
}

// MatchedPolicyIsNil applies the IsNil predicate on the "matched_policy" field.
func MatchedPolicyIsNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIsNull(FieldMatchedPolicy))
}

// MatchedPolicyNotNil applies the NotNil predicate on the "matched_policy" field.
func MatchedPolicyNotNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotNull(FieldMatchedPolicy))
}

// MatchedPolicyEqualFold applies the EqualFold predicate on the "matched_policy" field.
func MatchedPolicyEqualFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEqualFold(FieldMatchedPolicy, v))
}

// MatchedPolicyContainsFold applies the ContainsFold predicate on the "matched_policy" field.
func MatchedPolicyContainsFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContainsFold(FieldMatchedPolicy, v))
}

// MatchedGrantEQ applies the EQ predicate on the "matched_grant" field.
func MatchedGrantEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldMatchedGrant, v))
}

// MatchedGrantNEQ applies the NEQ predicate on the "matched_grant" field.
func MatchedGrantNEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldMatchedGrant, v))
}

// MatchedGrantIn applies the In predicate on the "matched_grant" field.
func MatchedGrantIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldMatchedGrant, vs...))
}

// MatchedGrantNotIn applies the NotIn predicate on the "matched_grant" field.
func MatchedGrantNotIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldMatchedGrant, vs...))
}

// MatchedGrantGT applies the GT predicate on the "matched_grant" field.
func MatchedGrantGT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldMatchedGrant, v))
}

// MatchedGrantGTE applies the GTE predicate on the "matched_grant" field.
func MatchedGrantGTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldMatchedGrant, v))
}

// MatchedGrantLT applies the LT predicate on the "matched_grant" field.
func MatchedGrantLT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldMatchedGrant, v))
}

// MatchedGrantLTE applies the LTE predicate on the "matched_grant" field.
func MatchedGrantLTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldMatchedGrant, v))
}

// MatchedGrantContains applies the Contains predicate on the "matched_grant" field.
func MatchedGrantContains(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContains(FieldMatchedGrant, v))
}

// MatchedGrantHasPrefix applies the HasPrefix predicate on the "matched_grant" field.
func MatchedGrantHasPrefix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasPrefix(FieldMatchedGrant, v))
}

// MatchedGrantHasSuffix applies the HasSuffix predicate on the "matched_grant" field.
func MatchedGrantHasSuffix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasSuffix(FieldMatchedGrant, v))
}

// MatchedGrantIsNil applies the IsNil predicate on the "matched_grant" field.
func MatchedGrantIsNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIsNull(FieldMatchedGrant))
}

// MatchedGrantNotNil applies the NotNil predicate on the "matched_grant" field.
func MatchedGrantNotNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotNull(FieldMatchedGrant))
}

// MatchedGrantEqualFold applies the EqualFold predicate on the "matched_grant" field.
func MatchedGrantEqualFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEqualFold(FieldMatchedGrant, v))
}

// MatchedGrantContainsFold applies the ContainsFold predicate on the "matched_grant" field.
func MatchedGrantContainsFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContainsFold(FieldMatchedGrant, v))
}

// PolicyIDEQ applies the EQ predicate on the "policy_id" field.
func PolicyIDEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldPolicyID, v))
}

// PolicyIDNEQ applies the NEQ predicate on the "policy_id" field.
func PolicyIDNEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldPolicyID, v))
}

// PolicyIDIn applies the In predicate on the "policy_id" field.
func PolicyIDIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldPolicyID, vs...))
}

// PolicyIDNotIn applies the NotIn predicate on the "policy_id" field.
func PolicyIDNotIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldPolicyID, vs...))
}

// PolicyIDGT applies the GT predicate on the "policy_id" field.
func PolicyIDGT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldPolicyID, v))
}

// PolicyIDGTE applies the GTE predicate on the "policy_id" field.
func PolicyIDGTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldPolicyID, v))
}

// PolicyIDLT applies the LT predicate on the "policy_id" field.
func PolicyIDLT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldPolicyID, v))
}

// PolicyIDLTE applies the LTE predicate on the "policy_id" field.
func PolicyIDLTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldPolicyID, v))
}

// PolicyIDContains applies the Contains predicate on the "policy_id" field.
func PolicyIDContains(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContains(FieldPolicyID, v))
}

// PolicyIDHasPrefix applies the HasPrefix predicate on the "policy_id" field.
func PolicyIDHasPrefix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasPrefix(FieldPolicyID, v))
}

// PolicyIDHasSuffix applies the HasSuffix predicate on the "policy_id" field.
func PolicyIDHasSuffix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasSuffix(FieldPolicyID, v))
}

// PolicyIDIsNil applies the IsNil predicate on the "policy_id" field.
func PolicyIDIsNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIsNull(FieldPolicyID))
}

// PolicyIDNotNil applies the NotNil predicate on the "policy_id" field.
func PolicyIDNotNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotNull(FieldPolicyID))
}

// PolicyIDEqualFold applies the EqualFold predicate on the "policy_id" field.
func PolicyIDEqualFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEqualFold(FieldPolicyID, v))
}

// PolicyIDContainsFold applies the ContainsFold predicate on the "policy_id" field.
func PolicyIDContainsFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContainsFold(FieldPolicyID, v))
}

// CorrelationIDEQ applies the EQ predicate on the "correlation_id" field.
func CorrelationIDEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldCorrelationID, v))
}

// CorrelationIDNEQ applies the NEQ predicate on the "correlation_id" field.
func CorrelationIDNEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldCorrelationID, v))
}

// CorrelationIDIn applies the In predicate on the "correlation_id" field.
func CorrelationIDIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldCorrelationID, vs...))
}

// CorrelationIDNotIn applies the NotIn predicate on the "correlation_id" field.
func CorrelationIDNotIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldCorrelationID, vs...))
}

// CorrelationIDGT applies the GT predicate on the "correlation_id" field.
func CorrelationIDGT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldCorrelationID, v))
}

// CorrelationIDGTE applies the GTE predicate on the "correlation_id" field.
func CorrelationIDGTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldCorrelationID, v))
}

// CorrelationIDLT applies the LT predicate on the "correlation_id" field.
func CorrelationIDLT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldCorrelationID, v))
}

// CorrelationIDLTE applies the LTE predicate on the "correlation_id" field.
func CorrelationIDLTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldCorrelationID, v))
}

// CorrelationIDContains applies the Contains predicate on the "correlation_id" field.
func CorrelationIDContains(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContains(FieldCorrelationID, v))
}

// CorrelationIDHasPrefix applies the HasPrefix predicate on the "correlation_id" field.
func CorrelationIDHasPrefix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasPrefix(FieldCorrelationID, v))
}

// CorrelationIDHasSuffix applies the HasSuffix predicate on the "correlation_id" field.
func CorrelationIDHasSuffix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasSuffix(FieldCorrelationID, v))
}

// CorrelationIDIsNil applies the IsNil predicate on the "correlation_id" field.
func CorrelationIDIsNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIsNull(FieldCorrelationID))
}

// CorrelationIDNotNil applies the NotNil predicate on the "correlation_id" field.
func CorrelationIDNotNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotNull(FieldCorrelationID))
}

// CorrelationIDEqualFold applies the EqualFold predicate on the "correlation_id" field.
func CorrelationIDEqualFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEqualFold(FieldCorrelationID, v))
}

// CorrelationIDContainsFold applies the ContainsFold predicate on the "correlation_id" field.
func CorrelationIDContainsFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContainsFold(FieldCorrelationID, v))
}

// SampledEQ applies the EQ predicate on the "sampled" field.
func SampledEQ(v bool) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldSampled, v))
}

// SampledNEQ applies the NEQ predicate on the "sampled" field.
func SampledNEQ(v bool) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldSampled, v))
}

// PermissionIDEQ applies the EQ predicate on the "permission_id" field.
func PermissionIDEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldPermissionID, v))
}

// PermissionIDNEQ applies the NEQ predicate on the "permission_id" field.
func PermissionIDNEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldPermissionID, v))
}

// PermissionIDIn applies the In predicate on the "permission_id" field.
func PermissionIDIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldPermissionID, vs...))
}

// PermissionIDNotIn applies the NotIn predicate on the "permission_id" field.
func PermissionIDNotIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldPermissionID, vs...))
}

// PermissionIDGT applies the GT predicate on the "permission_id" field.
func PermissionIDGT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldPermissionID, v))
}

// PermissionIDGTE applies the GTE predicate on the "permission_id" field.
func PermissionIDGTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldPermissionID, v))
}

// PermissionIDLT applies the LT predicate on the "permission_id" field.
func PermissionIDLT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldPermissionID, v))
}

// PermissionIDLTE applies the LTE predicate on the "permission_id" field.
func PermissionIDLTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldPermissionID, v))
}

// PermissionIDContains applies the Contains predicate on the "permission_id" field.
func PermissionIDContains(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContains(FieldPermissionID, v))
}

// PermissionIDHasPrefix applies the HasPrefix predicate on the "permission_id" field.
func PermissionIDHasPrefix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasPrefix(FieldPermissionID, v))
}

// PermissionIDHasSuffix applies the HasSuffix predicate on the "permission_id" field.
func PermissionIDHasSuffix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasSuffix(FieldPermissionID, v))
}

// PermissionIDIsNil applies the IsNil predicate on the "permission_id" field.
func PermissionIDIsNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIsNull(FieldPermissionID))
}

// PermissionIDNotNil applies the NotNil predicate on the "permission_id" field.
func PermissionIDNotNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotNull(FieldPermissionID))
}

// PermissionIDEqualFold applies the EqualFold predicate on the "permission_id" field.
func PermissionIDEqualFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEqualFold(FieldPermissionID, v))
}

// PermissionIDContainsFold applies the ContainsFold predicate on the "permission_id" field.
func PermissionIDContainsFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContainsFold(FieldPermissionID, v))
}

// CredentialNameEQ applies the EQ predicate on the "credential_name" field.
func CredentialNameEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldCredentialName, v))
}

// CredentialNameNEQ applies the NEQ predicate on the "credential_name" field.
func CredentialNameNEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldCredentialName, v))
}

// CredentialNameIn applies the In predicate on the "credential_name" field.
func CredentialNameIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldCredentialName, vs...))
}

// CredentialNameNotIn applies the NotIn predicate on the "credential_name" field.
func CredentialNameNotIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldCredentialName, vs...))
}

// CredentialNameGT applies the GT predicate on the "credential_name" field.
func CredentialNameGT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldCredentialName, v))
}

// CredentialNameGTE applies the GTE predicate on the "credential_name" field.
func CredentialNameGTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldCredentialName, v))
}

// CredentialNameLT applies the LT predicate on the "credential_name" field.
func CredentialNameLT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldCredentialName, v))
}

// CredentialNameLTE applies the LTE predicate on the "credential_name" field.
func CredentialNameLTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldCredentialName, v))
}

// CredentialNameContains applies the Contains predicate on the "credential_name" field.
func CredentialNameContains(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContains(FieldCredentialName, v))
}

// CredentialNameHasPrefix applies the HasPrefix predicate on the "credential_name" field.
func CredentialNameHasPrefix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasPrefix(FieldCredentialName, v))
}

// CredentialNameHasSuffix applies the HasSuffix predicate on the "credential_name" field.
func CredentialNameHasSuffix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasSuffix(FieldCredentialName, v))
}

// CredentialNameIsNil applies the IsNil predicate on the "credential_name" field.
func CredentialNameIsNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIsNull(FieldCredentialName))
}

// CredentialNameNotNil applies the NotNil predicate on the "credential_name" field.
func CredentialNameNotNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotNull(FieldCredentialName))
}

// CredentialNameEqualFold applies the EqualFold predicate on the "credential_name" field.
func CredentialNameEqualFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEqualFold(FieldCredentialName, v))
}

// CredentialNameContainsFold applies the ContainsFold predicate on the "credential_name" field.
func CredentialNameContainsFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContainsFold(FieldCredentialName, v))
}

// CredentialBoundaryKindEQ applies the EQ predicate on the "credential_boundary_kind" field.
func CredentialBoundaryKindEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldCredentialBoundaryKind, v))
}

// CredentialBoundaryKindNEQ applies the NEQ predicate on the "credential_boundary_kind" field.
func CredentialBoundaryKindNEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldCredentialBoundaryKind, v))
}

// CredentialBoundaryKindIn applies the In predicate on the "credential_boundary_kind" field.
func CredentialBoundaryKindIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldCredentialBoundaryKind, vs...))
}

// CredentialBoundaryKindNotIn applies the NotIn predicate on the "credential_boundary_kind" field.
func CredentialBoundaryKindNotIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldCredentialBoundaryKind, vs...))
}

// CredentialBoundaryKindGT applies the GT predicate on the "credential_boundary_kind" field.
func CredentialBoundaryKindGT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldCredentialBoundaryKind, v))
}

// CredentialBoundaryKindGTE applies the GTE predicate on the "credential_boundary_kind" field.
func CredentialBoundaryKindGTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldCredentialBoundaryKind, v))
}

// CredentialBoundaryKindLT applies the LT predicate on the "credential_boundary_kind" field.
func CredentialBoundaryKindLT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldCredentialBoundaryKind, v))
}

// CredentialBoundaryKindLTE applies the LTE predicate on the "credential_boundary_kind" field.
func CredentialBoundaryKindLTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldCredentialBoundaryKind, v))
}

// CredentialBoundaryKindContains applies the Contains predicate on the "credential_boundary_kind" field.
func CredentialBoundaryKindContains(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContains(FieldCredentialBoundaryKind, v))
}

// CredentialBoundaryKindHasPrefix applies the HasPrefix predicate on the "credential_boundary_kind" field.
func CredentialBoundaryKindHasPrefix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasPrefix(FieldCredentialBoundaryKind, v))
}

// CredentialBoundaryKindHasSuffix applies the HasSuffix predicate on the "credential_boundary_kind" field.
func CredentialBoundaryKindHasSuffix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasSuffix(FieldCredentialBoundaryKind, v))
}

// CredentialBoundaryKindIsNil applies the IsNil predicate on the "credential_boundary_kind" field.
func CredentialBoundaryKindIsNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIsNull(FieldCredentialBoundaryKind))
}

// CredentialBoundaryKindNotNil applies the NotNil predicate on the "credential_boundary_kind" field.
func CredentialBoundaryKindNotNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotNull(FieldCredentialBoundaryKind))
}

// CredentialBoundaryKindEqualFold applies the EqualFold predicate on the "credential_boundary_kind" field.
func CredentialBoundaryKindEqualFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEqualFold(FieldCredentialBoundaryKind, v))
}

// CredentialBoundaryKindContainsFold applies the ContainsFold predicate on the "credential_boundary_kind" field.
func CredentialBoundaryKindContainsFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContainsFold(FieldCredentialBoundaryKind, v))
}

// CredentialBoundaryProjectIDEQ applies the EQ predicate on the "credential_boundary_project_id" field.
func CredentialBoundaryProjectIDEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldCredentialBoundaryProjectID, v))
}

// CredentialBoundaryProjectIDNEQ applies the NEQ predicate on the "credential_boundary_project_id" field.
func CredentialBoundaryProjectIDNEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldCredentialBoundaryProjectID, v))
}

// CredentialBoundaryProjectIDIn applies the In predicate on the "credential_boundary_project_id" field.
func CredentialBoundaryProjectIDIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldCredentialBoundaryProjectID, vs...))
}

// CredentialBoundaryProjectIDNotIn applies the NotIn predicate on the "credential_boundary_project_id" field.
func CredentialBoundaryProjectIDNotIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldCredentialBoundaryProjectID, vs...))
}

// CredentialBoundaryProjectIDGT applies the GT predicate on the "credential_boundary_project_id" field.
func CredentialBoundaryProjectIDGT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldCredentialBoundaryProjectID, v))
}

// CredentialBoundaryProjectIDGTE applies the GTE predicate on the "credential_boundary_project_id" field.
func CredentialBoundaryProjectIDGTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldCredentialBoundaryProjectID, v))
}

// CredentialBoundaryProjectIDLT applies the LT predicate on the "credential_boundary_project_id" field.
func CredentialBoundaryProjectIDLT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldCredentialBoundaryProjectID, v))
}

// CredentialBoundaryProjectIDLTE applies the LTE predicate on the "credential_boundary_project_id" field.
func CredentialBoundaryProjectIDLTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldCredentialBoundaryProjectID, v))
}

// CredentialBoundaryProjectIDContains applies the Contains predicate on the "credential_boundary_project_id" field.
func CredentialBoundaryProjectIDContains(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContains(FieldCredentialBoundaryProjectID, v))
}

// CredentialBoundaryProjectIDHasPrefix applies the HasPrefix predicate on the "credential_boundary_project_id" field.
func CredentialBoundaryProjectIDHasPrefix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasPrefix(FieldCredentialBoundaryProjectID, v))
}

// CredentialBoundaryProjectIDHasSuffix applies the HasSuffix predicate on the "credential_boundary_project_id" field.
func CredentialBoundaryProjectIDHasSuffix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasSuffix(FieldCredentialBoundaryProjectID, v))
}

// CredentialBoundaryProjectIDIsNil applies the IsNil predicate on the "credential_boundary_project_id" field.
func CredentialBoundaryProjectIDIsNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIsNull(FieldCredentialBoundaryProjectID))
}

// CredentialBoundaryProjectIDNotNil applies the NotNil predicate on the "credential_boundary_project_id" field.
func CredentialBoundaryProjectIDNotNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotNull(FieldCredentialBoundaryProjectID))
}

// CredentialBoundaryProjectIDEqualFold applies the EqualFold predicate on the "credential_boundary_project_id" field.
func CredentialBoundaryProjectIDEqualFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEqualFold(FieldCredentialBoundaryProjectID, v))
}

// CredentialBoundaryProjectIDContainsFold applies the ContainsFold predicate on the "credential_boundary_project_id" field.
func CredentialBoundaryProjectIDContainsFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContainsFold(FieldCredentialBoundaryProjectID, v))
}

// CredentialLabelsEQ applies the EQ predicate on the "credential_labels" field.
func CredentialLabelsEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldCredentialLabels, v))
}

// CredentialLabelsNEQ applies the NEQ predicate on the "credential_labels" field.
func CredentialLabelsNEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldCredentialLabels, v))
}

// CredentialLabelsIn applies the In predicate on the "credential_labels" field.
func CredentialLabelsIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldCredentialLabels, vs...))
}

// CredentialLabelsNotIn applies the NotIn predicate on the "credential_labels" field.
func CredentialLabelsNotIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldCredentialLabels, vs...))
}

// CredentialLabelsGT applies the GT predicate on the "credential_labels" field.
func CredentialLabelsGT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldCredentialLabels, v))
}

// CredentialLabelsGTE applies the GTE predicate on the "credential_labels" field.
func CredentialLabelsGTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldCredentialLabels, v))
}

// CredentialLabelsLT applies the LT predicate on the "credential_labels" field.
func CredentialLabelsLT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldCredentialLabels, v))
}

// CredentialLabelsLTE applies the LTE predicate on the "credential_labels" field.
func CredentialLabelsLTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldCredentialLabels, v))
}

// CredentialLabelsContains applies the Contains predicate on the "credential_labels" field.
func CredentialLabelsContains(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContains(FieldCredentialLabels, v))
}

// CredentialLabelsHasPrefix applies the HasPrefix predicate on the "credential_labels" field.
func CredentialLabelsHasPrefix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasPrefix(FieldCredentialLabels, v))
}

// CredentialLabelsHasSuffix applies the HasSuffix predicate on the "credential_labels" field.
func CredentialLabelsHasSuffix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasSuffix(FieldCredentialLabels, v))
}

// CredentialLabelsIsNil applies the IsNil predicate on the "credential_labels" field.
func CredentialLabelsIsNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIsNull(FieldCredentialLabels))
}

// CredentialLabelsNotNil applies the NotNil predicate on the "credential_labels" field.
func CredentialLabelsNotNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotNull(FieldCredentialLabels))
}

// CredentialLabelsEqualFold applies the EqualFold predicate on the "credential_labels" field.
func CredentialLabelsEqualFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEqualFold(FieldCredentialLabels, v))
}

// CredentialLabelsContainsFold applies the ContainsFold predicate on the "credential_labels" field.
func CredentialLabelsContainsFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContainsFold(FieldCredentialLabels, v))
}

// ExecutorKindEQ applies the EQ predicate on the "executor_kind" field.
func ExecutorKindEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldExecutorKind, v))
}

// ExecutorKindNEQ applies the NEQ predicate on the "executor_kind" field.
func ExecutorKindNEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldExecutorKind, v))
}

// ExecutorKindIn applies the In predicate on the "executor_kind" field.
func ExecutorKindIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldExecutorKind, vs...))
}

// ExecutorKindNotIn applies the NotIn predicate on the "executor_kind" field.
func ExecutorKindNotIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldExecutorKind, vs...))
}

// ExecutorKindGT applies the GT predicate on the "executor_kind" field.
func ExecutorKindGT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldExecutorKind, v))
}

// ExecutorKindGTE applies the GTE predicate on the "executor_kind" field.
func ExecutorKindGTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldExecutorKind, v))
}

// ExecutorKindLT applies the LT predicate on the "executor_kind" field.
func ExecutorKindLT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldExecutorKind, v))
}

// ExecutorKindLTE applies the LTE predicate on the "executor_kind" field.
func ExecutorKindLTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldExecutorKind, v))
}

// ExecutorKindContains applies the Contains predicate on the "executor_kind" field.
func ExecutorKindContains(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContains(FieldExecutorKind, v))
}

// ExecutorKindHasPrefix applies the HasPrefix predicate on the "executor_kind" field.
func ExecutorKindHasPrefix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasPrefix(FieldExecutorKind, v))
}

// ExecutorKindHasSuffix applies the HasSuffix predicate on the "executor_kind" field.
func ExecutorKindHasSuffix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasSuffix(FieldExecutorKind, v))
}

// ExecutorKindIsNil applies the IsNil predicate on the "executor_kind" field.
func ExecutorKindIsNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIsNull(FieldExecutorKind))
}

// ExecutorKindNotNil applies the NotNil predicate on the "executor_kind" field.
func ExecutorKindNotNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotNull(FieldExecutorKind))
}

// ExecutorKindEqualFold applies the EqualFold predicate on the "executor_kind" field.
func ExecutorKindEqualFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEqualFold(FieldExecutorKind, v))
}

// ExecutorKindContainsFold applies the ContainsFold predicate on the "executor_kind" field.
func ExecutorKindContainsFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContainsFold(FieldExecutorKind, v))
}

// ExecutorIDEQ applies the EQ predicate on the "executor_id" field.
func ExecutorIDEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldExecutorID, v))
}

// ExecutorIDNEQ applies the NEQ predicate on the "executor_id" field.
func ExecutorIDNEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldExecutorID, v))
}

// ExecutorIDIn applies the In predicate on the "executor_id" field.
func ExecutorIDIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldExecutorID, vs...))
}

// ExecutorIDNotIn applies the NotIn predicate on the "executor_id" field.
func ExecutorIDNotIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldExecutorID, vs...))
}

// ExecutorIDGT applies the GT predicate on the "executor_id" field.
func ExecutorIDGT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldExecutorID, v))
}

// ExecutorIDGTE applies the GTE predicate on the "executor_id" field.
func ExecutorIDGTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldExecutorID, v))
}

// ExecutorIDLT applies the LT predicate on the "executor_id" field.
func ExecutorIDLT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldExecutorID, v))
}

// ExecutorIDLTE applies the LTE predicate on the "executor_id" field.
func ExecutorIDLTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldExecutorID, v))
}

// ExecutorIDContains applies the Contains predicate on the "executor_id" field.
func ExecutorIDContains(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContains(FieldExecutorID, v))
}

// ExecutorIDHasPrefix applies the HasPrefix predicate on the "executor_id" field.
func ExecutorIDHasPrefix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasPrefix(FieldExecutorID, v))
}

// ExecutorIDHasSuffix applies the HasSuffix predicate on the "executor_id" field.
func ExecutorIDHasSuffix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasSuffix(FieldExecutorID, v))
}

// ExecutorIDIsNil applies the IsNil predicate on the "executor_id" field.
func ExecutorIDIsNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIsNull(FieldExecutorID))
}

// ExecutorIDNotNil applies the NotNil predicate on the "executor_id" field.
func ExecutorIDNotNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotNull(FieldExecutorID))
}

// ExecutorIDEqualFold applies the EqualFold predicate on the "executor_id" field.
func ExecutorIDEqualFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEqualFold(FieldExecutorID, v))
}

// ExecutorIDContainsFold applies the ContainsFold predicate on the "executor_id" field.
func ExecutorIDContainsFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContainsFold(FieldExecutorID, v))
}

// DeniedByEQ applies the EQ predicate on the "denied_by" field.
func DeniedByEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEQ(FieldDeniedBy, v))
}

// DeniedByNEQ applies the NEQ predicate on the "denied_by" field.
func DeniedByNEQ(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNEQ(FieldDeniedBy, v))
}

// DeniedByIn applies the In predicate on the "denied_by" field.
func DeniedByIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIn(FieldDeniedBy, vs...))
}

// DeniedByNotIn applies the NotIn predicate on the "denied_by" field.
func DeniedByNotIn(vs ...string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotIn(FieldDeniedBy, vs...))
}

// DeniedByGT applies the GT predicate on the "denied_by" field.
func DeniedByGT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGT(FieldDeniedBy, v))
}

// DeniedByGTE applies the GTE predicate on the "denied_by" field.
func DeniedByGTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldGTE(FieldDeniedBy, v))
}

// DeniedByLT applies the LT predicate on the "denied_by" field.
func DeniedByLT(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLT(FieldDeniedBy, v))
}

// DeniedByLTE applies the LTE predicate on the "denied_by" field.
func DeniedByLTE(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldLTE(FieldDeniedBy, v))
}

// DeniedByContains applies the Contains predicate on the "denied_by" field.
func DeniedByContains(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContains(FieldDeniedBy, v))
}

// DeniedByHasPrefix applies the HasPrefix predicate on the "denied_by" field.
func DeniedByHasPrefix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasPrefix(FieldDeniedBy, v))
}

// DeniedByHasSuffix applies the HasSuffix predicate on the "denied_by" field.
func DeniedByHasSuffix(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldHasSuffix(FieldDeniedBy, v))
}

// DeniedByIsNil applies the IsNil predicate on the "denied_by" field.
func DeniedByIsNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldIsNull(FieldDeniedBy))
}

// DeniedByNotNil applies the NotNil predicate on the "denied_by" field.
func DeniedByNotNil() predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldNotNull(FieldDeniedBy))
}

// DeniedByEqualFold applies the EqualFold predicate on the "denied_by" field.
func DeniedByEqualFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldEqualFold(FieldDeniedBy, v))
}

// DeniedByContainsFold applies the ContainsFold predicate on the "denied_by" field.
func DeniedByContainsFold(v string) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.FieldContainsFold(FieldDeniedBy, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DecisionAudit) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DecisionAudit) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DecisionAudit) predicate.DecisionAudit {
	return predicate.DecisionAudit(sql.NotPredicates(p))
}
