// Code generated by ent, DO NOT EDIT.

package accessconstrainthistory

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the accessconstrainthistory type in the database.
	Label = "access_constraint_history"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "event_id"
	// FieldConstraintID holds the string denoting the constraint_id field in the database.
	FieldConstraintID = "constraint_id"
	// FieldOccurredAt holds the string denoting the occurred_at field in the database.
	FieldOccurredAt = "occurred_at"
	// FieldOperation holds the string denoting the operation field in the database.
	FieldOperation = "operation"
	// FieldActorKind holds the string denoting the actor_kind field in the database.
	FieldActorKind = "actor_kind"
	// FieldActorID holds the string denoting the actor_id field in the database.
	FieldActorID = "actor_id"
	// FieldCorrelationID holds the string denoting the correlation_id field in the database.
	FieldCorrelationID = "correlation_id"
	// FieldBatchOperationID holds the string denoting the batch_operation_id field in the database.
	FieldBatchOperationID = "batch_operation_id"
	// FieldBeforeRevision holds the string denoting the before_revision field in the database.
	FieldBeforeRevision = "before_revision"
	// FieldAfterRevision holds the string denoting the after_revision field in the database.
	FieldAfterRevision = "after_revision"
	// FieldClassification holds the string denoting the classification field in the database.
	FieldClassification = "classification"
	// FieldPreviewID holds the string denoting the preview_id field in the database.
	FieldPreviewID = "preview_id"
	// FieldDraftHash holds the string denoting the draft_hash field in the database.
	FieldDraftHash = "draft_hash"
	// FieldImpactCountsJSON holds the string denoting the impact_counts_json field in the database.
	FieldImpactCountsJSON = "impact_counts_json"
	// FieldChangedFieldsJSON holds the string denoting the changed_fields_json field in the database.
	FieldChangedFieldsJSON = "changed_fields_json"
	// EdgeConstraint holds the string denoting the constraint edge name in mutations.
	EdgeConstraint = "constraint"
	// AccessConstraintFieldID holds the string denoting the ID field of the AccessConstraint.
	AccessConstraintFieldID = "id"
	// Table holds the table name of the accessconstrainthistory in the database.
	Table = "access_constraint_history"
	// ConstraintTable is the table that holds the constraint relation/edge.
	ConstraintTable = "access_constraint_history"
	// ConstraintInverseTable is the table name for the AccessConstraint entity.
	// It exists in this package in order to avoid circular dependency with the "accessconstraint" package.
	ConstraintInverseTable = "access_constraints"
	// ConstraintColumn is the table column denoting the constraint relation/edge.
	ConstraintColumn = "constraint_id"
)

// Columns holds all SQL columns for accessconstrainthistory fields.
var Columns = []string{
	FieldID,
	FieldConstraintID,
	FieldOccurredAt,
	FieldOperation,
	FieldActorKind,
	FieldActorID,
	FieldCorrelationID,
	FieldBatchOperationID,
	FieldBeforeRevision,
	FieldAfterRevision,
	FieldClassification,
	FieldPreviewID,
	FieldDraftHash,
	FieldImpactCountsJSON,
	FieldChangedFieldsJSON,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// OperationValidator is a validator for the "operation" field. It is called by the builders before save.
	OperationValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the AccessConstraintHistory queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByConstraintID orders the results by the constraint_id field.
func ByConstraintID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConstraintID, opts...).ToFunc()
}

// ByOccurredAt orders the results by the occurred_at field.
func ByOccurredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOccurredAt, opts...).ToFunc()
}

// ByOperation orders the results by the operation field.
func ByOperation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperation, opts...).ToFunc()
}

// ByActorKind orders the results by the actor_kind field.
func ByActorKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorKind, opts...).ToFunc()
}

// ByActorID orders the results by the actor_id field.
func ByActorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorID, opts...).ToFunc()
}

// ByCorrelationID orders the results by the correlation_id field.
func ByCorrelationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCorrelationID, opts...).ToFunc()
}

// ByBatchOperationID orders the results by the batch_operation_id field.
func ByBatchOperationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBatchOperationID, opts...).ToFunc()
}

// ByBeforeRevision orders the results by the before_revision field.
func ByBeforeRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBeforeRevision, opts...).ToFunc()
}

// ByAfterRevision orders the results by the after_revision field.
func ByAfterRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAfterRevision, opts...).ToFunc()
}

// ByClassification orders the results by the classification field.
func ByClassification(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClassification, opts...).ToFunc()
}

// ByPreviewID orders the results by the preview_id field.
func ByPreviewID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreviewID, opts...).ToFunc()
}

// ByDraftHash orders the results by the draft_hash field.
func ByDraftHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDraftHash, opts...).ToFunc()
}

// ByImpactCountsJSON orders the results by the impact_counts_json field.
func ByImpactCountsJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImpactCountsJSON, opts...).ToFunc()
}

// ByChangedFieldsJSON orders the results by the changed_fields_json field.
func ByChangedFieldsJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChangedFieldsJSON, opts...).ToFunc()
}

// ByConstraintField orders the results by constraint field.
func ByConstraintField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConstraintStep(), sql.OrderByField(field, opts...))
	}
}
func newConstraintStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConstraintInverseTable, AccessConstraintFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ConstraintTable, ConstraintColumn),
	)
}
