// Code generated by ent, DO NOT EDIT.

package accessconstrainthistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldContainsFold(FieldID, id))
}

// ConstraintID applies equality check predicate on the "constraint_id" field. It's identical to ConstraintIDEQ.
func ConstraintID(v uuid.UUID) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldConstraintID, v))
}

// OccurredAt applies equality check predicate on the "occurred_at" field. It's identical to OccurredAtEQ.
func OccurredAt(v time.Time) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldOccurredAt, v))
}

// Operation applies equality check predicate on the "operation" field. It's identical to OperationEQ.
func Operation(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldOperation, v))
}

// ActorKind applies equality check predicate on the "actor_kind" field. It's identical to ActorKindEQ.
func ActorKind(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldActorKind, v))
}

// ActorID applies equality check predicate on the "actor_id" field. It's identical to ActorIDEQ.
func ActorID(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldActorID, v))
}

// CorrelationID applies equality check predicate on the "correlation_id" field. It's identical to CorrelationIDEQ.
func CorrelationID(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldCorrelationID, v))
}

// BatchOperationID applies equality check predicate on the "batch_operation_id" field. It's identical to BatchOperationIDEQ.
func BatchOperationID(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldBatchOperationID, v))
}

// BeforeRevision applies equality check predicate on the "before_revision" field. It's identical to BeforeRevisionEQ.
func BeforeRevision(v int64) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldBeforeRevision, v))
}

// AfterRevision applies equality check predicate on the "after_revision" field. It's identical to AfterRevisionEQ.
func AfterRevision(v int64) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldAfterRevision, v))
}

// Classification applies equality check predicate on the "classification" field. It's identical to ClassificationEQ.
func Classification(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldClassification, v))
}

// PreviewID applies equality check predicate on the "preview_id" field. It's identical to PreviewIDEQ.
func PreviewID(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldPreviewID, v))
}

// DraftHash applies equality check predicate on the "draft_hash" field. It's identical to DraftHashEQ.
func DraftHash(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldDraftHash, v))
}

// ImpactCountsJSON applies equality check predicate on the "impact_counts_json" field. It's identical to ImpactCountsJSONEQ.
func ImpactCountsJSON(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldImpactCountsJSON, v))
}

// ChangedFieldsJSON applies equality check predicate on the "changed_fields_json" field. It's identical to ChangedFieldsJSONEQ.
func ChangedFieldsJSON(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldChangedFieldsJSON, v))
}

// ConstraintIDEQ applies the EQ predicate on the "constraint_id" field.
func ConstraintIDEQ(v uuid.UUID) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldConstraintID, v))
}

// ConstraintIDNEQ applies the NEQ predicate on the "constraint_id" field.
func ConstraintIDNEQ(v uuid.UUID) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNEQ(FieldConstraintID, v))
}

// ConstraintIDIn applies the In predicate on the "constraint_id" field.
func ConstraintIDIn(vs ...uuid.UUID) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIn(FieldConstraintID, vs...))
}

// ConstraintIDNotIn applies the NotIn predicate on the "constraint_id" field.
func ConstraintIDNotIn(vs ...uuid.UUID) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotIn(FieldConstraintID, vs...))
}

// OccurredAtEQ applies the EQ predicate on the "occurred_at" field.
func OccurredAtEQ(v time.Time) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldOccurredAt, v))
}

// OccurredAtNEQ applies the NEQ predicate on the "occurred_at" field.
func OccurredAtNEQ(v time.Time) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNEQ(FieldOccurredAt, v))
}

// OccurredAtIn applies the In predicate on the "occurred_at" field.
func OccurredAtIn(vs ...time.Time) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIn(FieldOccurredAt, vs...))
}

// OccurredAtNotIn applies the NotIn predicate on the "occurred_at" field.
func OccurredAtNotIn(vs ...time.Time) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotIn(FieldOccurredAt, vs...))
}

// OccurredAtGT applies the GT predicate on the "occurred_at" field.
func OccurredAtGT(v time.Time) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGT(FieldOccurredAt, v))
}

// OccurredAtGTE applies the GTE predicate on the "occurred_at" field.
func OccurredAtGTE(v time.Time) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGTE(FieldOccurredAt, v))
}

// OccurredAtLT applies the LT predicate on the "occurred_at" field.
func OccurredAtLT(v time.Time) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLT(FieldOccurredAt, v))
}

// OccurredAtLTE applies the LTE predicate on the "occurred_at" field.
func OccurredAtLTE(v time.Time) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLTE(FieldOccurredAt, v))
}

// OperationEQ applies the EQ predicate on the "operation" field.
func OperationEQ(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldOperation, v))
}

// OperationNEQ applies the NEQ predicate on the "operation" field.
func OperationNEQ(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNEQ(FieldOperation, v))
}

// OperationIn applies the In predicate on the "operation" field.
func OperationIn(vs ...string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIn(FieldOperation, vs...))
}

// OperationNotIn applies the NotIn predicate on the "operation" field.
func OperationNotIn(vs ...string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotIn(FieldOperation, vs...))
}

// OperationGT applies the GT predicate on the "operation" field.
func OperationGT(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGT(FieldOperation, v))
}

// OperationGTE applies the GTE predicate on the "operation" field.
func OperationGTE(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGTE(FieldOperation, v))
}

// OperationLT applies the LT predicate on the "operation" field.
func OperationLT(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLT(FieldOperation, v))
}

// OperationLTE applies the LTE predicate on the "operation" field.
func OperationLTE(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLTE(FieldOperation, v))
}

// OperationContains applies the Contains predicate on the "operation" field.
func OperationContains(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldContains(FieldOperation, v))
}

// OperationHasPrefix applies the HasPrefix predicate on the "operation" field.
func OperationHasPrefix(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldHasPrefix(FieldOperation, v))
}

// OperationHasSuffix applies the HasSuffix predicate on the "operation" field.
func OperationHasSuffix(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldHasSuffix(FieldOperation, v))
}

// OperationEqualFold applies the EqualFold predicate on the "operation" field.
func OperationEqualFold(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEqualFold(FieldOperation, v))
}

// OperationContainsFold applies the ContainsFold predicate on the "operation" field.
func OperationContainsFold(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldContainsFold(FieldOperation, v))
}

// ActorKindEQ applies the EQ predicate on the "actor_kind" field.
func ActorKindEQ(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldActorKind, v))
}

// ActorKindNEQ applies the NEQ predicate on the "actor_kind" field.
func ActorKindNEQ(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNEQ(FieldActorKind, v))
}

// ActorKindIn applies the In predicate on the "actor_kind" field.
func ActorKindIn(vs ...string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIn(FieldActorKind, vs...))
}

// ActorKindNotIn applies the NotIn predicate on the "actor_kind" field.
func ActorKindNotIn(vs ...string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotIn(FieldActorKind, vs...))
}

// ActorKindGT applies the GT predicate on the "actor_kind" field.
func ActorKindGT(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGT(FieldActorKind, v))
}

// ActorKindGTE applies the GTE predicate on the "actor_kind" field.
func ActorKindGTE(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGTE(FieldActorKind, v))
}

// ActorKindLT applies the LT predicate on the "actor_kind" field.
func ActorKindLT(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLT(FieldActorKind, v))
}

// ActorKindLTE applies the LTE predicate on the "actor_kind" field.
func ActorKindLTE(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLTE(FieldActorKind, v))
}

// ActorKindContains applies the Contains predicate on the "actor_kind" field.
func ActorKindContains(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldContains(FieldActorKind, v))
}

// ActorKindHasPrefix applies the HasPrefix predicate on the "actor_kind" field.
func ActorKindHasPrefix(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldHasPrefix(FieldActorKind, v))
}

// ActorKindHasSuffix applies the HasSuffix predicate on the "actor_kind" field.
func ActorKindHasSuffix(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldHasSuffix(FieldActorKind, v))
}

// ActorKindIsNil applies the IsNil predicate on the "actor_kind" field.
func ActorKindIsNil() predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIsNull(FieldActorKind))
}

// ActorKindNotNil applies the NotNil predicate on the "actor_kind" field.
func ActorKindNotNil() predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotNull(FieldActorKind))
}

// ActorKindEqualFold applies the EqualFold predicate on the "actor_kind" field.
func ActorKindEqualFold(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEqualFold(FieldActorKind, v))
}

// ActorKindContainsFold applies the ContainsFold predicate on the "actor_kind" field.
func ActorKindContainsFold(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldContainsFold(FieldActorKind, v))
}

// ActorIDEQ applies the EQ predicate on the "actor_id" field.
func ActorIDEQ(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldActorID, v))
}

// ActorIDNEQ applies the NEQ predicate on the "actor_id" field.
func ActorIDNEQ(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNEQ(FieldActorID, v))
}

// ActorIDIn applies the In predicate on the "actor_id" field.
func ActorIDIn(vs ...string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIn(FieldActorID, vs...))
}

// ActorIDNotIn applies the NotIn predicate on the "actor_id" field.
func ActorIDNotIn(vs ...string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotIn(FieldActorID, vs...))
}

// ActorIDGT applies the GT predicate on the "actor_id" field.
func ActorIDGT(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGT(FieldActorID, v))
}

// ActorIDGTE applies the GTE predicate on the "actor_id" field.
func ActorIDGTE(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGTE(FieldActorID, v))
}

// ActorIDLT applies the LT predicate on the "actor_id" field.
func ActorIDLT(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLT(FieldActorID, v))
}

// ActorIDLTE applies the LTE predicate on the "actor_id" field.
func ActorIDLTE(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLTE(FieldActorID, v))
}

// ActorIDContains applies the Contains predicate on the "actor_id" field.
func ActorIDContains(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldContains(FieldActorID, v))
}

// ActorIDHasPrefix applies the HasPrefix predicate on the "actor_id" field.
func ActorIDHasPrefix(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldHasPrefix(FieldActorID, v))
}

// ActorIDHasSuffix applies the HasSuffix predicate on the "actor_id" field.
func ActorIDHasSuffix(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldHasSuffix(FieldActorID, v))
}

// ActorIDIsNil applies the IsNil predicate on the "actor_id" field.
func ActorIDIsNil() predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIsNull(FieldActorID))
}

// ActorIDNotNil applies the NotNil predicate on the "actor_id" field.
func ActorIDNotNil() predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotNull(FieldActorID))
}

// ActorIDEqualFold applies the EqualFold predicate on the "actor_id" field.
func ActorIDEqualFold(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEqualFold(FieldActorID, v))
}

// ActorIDContainsFold applies the ContainsFold predicate on the "actor_id" field.
func ActorIDContainsFold(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldContainsFold(FieldActorID, v))
}

// CorrelationIDEQ applies the EQ predicate on the "correlation_id" field.
func CorrelationIDEQ(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldCorrelationID, v))
}

// CorrelationIDNEQ applies the NEQ predicate on the "correlation_id" field.
func CorrelationIDNEQ(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNEQ(FieldCorrelationID, v))
}

// CorrelationIDIn applies the In predicate on the "correlation_id" field.
func CorrelationIDIn(vs ...string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIn(FieldCorrelationID, vs...))
}

// CorrelationIDNotIn applies the NotIn predicate on the "correlation_id" field.
func CorrelationIDNotIn(vs ...string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotIn(FieldCorrelationID, vs...))
}

// CorrelationIDGT applies the GT predicate on the "correlation_id" field.
func CorrelationIDGT(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGT(FieldCorrelationID, v))
}

// CorrelationIDGTE applies the GTE predicate on the "correlation_id" field.
func CorrelationIDGTE(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGTE(FieldCorrelationID, v))
}

// CorrelationIDLT applies the LT predicate on the "correlation_id" field.
func CorrelationIDLT(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLT(FieldCorrelationID, v))
}

// CorrelationIDLTE applies the LTE predicate on the "correlation_id" field.
func CorrelationIDLTE(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLTE(FieldCorrelationID, v))
}

// CorrelationIDContains applies the Contains predicate on the "correlation_id" field.
func CorrelationIDContains(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldContains(FieldCorrelationID, v))
}

// CorrelationIDHasPrefix applies the HasPrefix predicate on the "correlation_id" field.
func CorrelationIDHasPrefix(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldHasPrefix(FieldCorrelationID, v))
}

// CorrelationIDHasSuffix applies the HasSuffix predicate on the "correlation_id" field.
func CorrelationIDHasSuffix(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldHasSuffix(FieldCorrelationID, v))
}

// CorrelationIDIsNil applies the IsNil predicate on the "correlation_id" field.
func CorrelationIDIsNil() predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIsNull(FieldCorrelationID))
}

// CorrelationIDNotNil applies the NotNil predicate on the "correlation_id" field.
func CorrelationIDNotNil() predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotNull(FieldCorrelationID))
}

// CorrelationIDEqualFold applies the EqualFold predicate on the "correlation_id" field.
func CorrelationIDEqualFold(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEqualFold(FieldCorrelationID, v))
}

// CorrelationIDContainsFold applies the ContainsFold predicate on the "correlation_id" field.
func CorrelationIDContainsFold(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldContainsFold(FieldCorrelationID, v))
}

// BatchOperationIDEQ applies the EQ predicate on the "batch_operation_id" field.
func BatchOperationIDEQ(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldBatchOperationID, v))
}

// BatchOperationIDNEQ applies the NEQ predicate on the "batch_operation_id" field.
func BatchOperationIDNEQ(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNEQ(FieldBatchOperationID, v))
}

// BatchOperationIDIn applies the In predicate on the "batch_operation_id" field.
func BatchOperationIDIn(vs ...string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIn(FieldBatchOperationID, vs...))
}

// BatchOperationIDNotIn applies the NotIn predicate on the "batch_operation_id" field.
func BatchOperationIDNotIn(vs ...string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotIn(FieldBatchOperationID, vs...))
}

// BatchOperationIDGT applies the GT predicate on the "batch_operation_id" field.
func BatchOperationIDGT(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGT(FieldBatchOperationID, v))
}

// BatchOperationIDGTE applies the GTE predicate on the "batch_operation_id" field.
func BatchOperationIDGTE(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGTE(FieldBatchOperationID, v))
}

// BatchOperationIDLT applies the LT predicate on the "batch_operation_id" field.
func BatchOperationIDLT(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLT(FieldBatchOperationID, v))
}

// BatchOperationIDLTE applies the LTE predicate on the "batch_operation_id" field.
func BatchOperationIDLTE(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLTE(FieldBatchOperationID, v))
}

// BatchOperationIDContains applies the Contains predicate on the "batch_operation_id" field.
func BatchOperationIDContains(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldContains(FieldBatchOperationID, v))
}

// BatchOperationIDHasPrefix applies the HasPrefix predicate on the "batch_operation_id" field.
func BatchOperationIDHasPrefix(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldHasPrefix(FieldBatchOperationID, v))
}

// BatchOperationIDHasSuffix applies the HasSuffix predicate on the "batch_operation_id" field.
func BatchOperationIDHasSuffix(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldHasSuffix(FieldBatchOperationID, v))
}

// BatchOperationIDIsNil applies the IsNil predicate on the "batch_operation_id" field.
func BatchOperationIDIsNil() predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIsNull(FieldBatchOperationID))
}

// BatchOperationIDNotNil applies the NotNil predicate on the "batch_operation_id" field.
func BatchOperationIDNotNil() predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotNull(FieldBatchOperationID))
}

// BatchOperationIDEqualFold applies the EqualFold predicate on the "batch_operation_id" field.
func BatchOperationIDEqualFold(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEqualFold(FieldBatchOperationID, v))
}

// BatchOperationIDContainsFold applies the ContainsFold predicate on the "batch_operation_id" field.
func BatchOperationIDContainsFold(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldContainsFold(FieldBatchOperationID, v))
}

// BeforeRevisionEQ applies the EQ predicate on the "before_revision" field.
func BeforeRevisionEQ(v int64) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldBeforeRevision, v))
}

// BeforeRevisionNEQ applies the NEQ predicate on the "before_revision" field.
func BeforeRevisionNEQ(v int64) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNEQ(FieldBeforeRevision, v))
}

// BeforeRevisionIn applies the In predicate on the "before_revision" field.
func BeforeRevisionIn(vs ...int64) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIn(FieldBeforeRevision, vs...))
}

// BeforeRevisionNotIn applies the NotIn predicate on the "before_revision" field.
func BeforeRevisionNotIn(vs ...int64) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotIn(FieldBeforeRevision, vs...))
}

// BeforeRevisionGT applies the GT predicate on the "before_revision" field.
func BeforeRevisionGT(v int64) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGT(FieldBeforeRevision, v))
}

// BeforeRevisionGTE applies the GTE predicate on the "before_revision" field.
func BeforeRevisionGTE(v int64) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGTE(FieldBeforeRevision, v))
}

// BeforeRevisionLT applies the LT predicate on the "before_revision" field.
func BeforeRevisionLT(v int64) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLT(FieldBeforeRevision, v))
}

// BeforeRevisionLTE applies the LTE predicate on the "before_revision" field.
func BeforeRevisionLTE(v int64) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLTE(FieldBeforeRevision, v))
}

// BeforeRevisionIsNil applies the IsNil predicate on the "before_revision" field.
func BeforeRevisionIsNil() predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIsNull(FieldBeforeRevision))
}

// BeforeRevisionNotNil applies the NotNil predicate on the "before_revision" field.
func BeforeRevisionNotNil() predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotNull(FieldBeforeRevision))
}

// AfterRevisionEQ applies the EQ predicate on the "after_revision" field.
func AfterRevisionEQ(v int64) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldAfterRevision, v))
}

// AfterRevisionNEQ applies the NEQ predicate on the "after_revision" field.
func AfterRevisionNEQ(v int64) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNEQ(FieldAfterRevision, v))
}

// AfterRevisionIn applies the In predicate on the "after_revision" field.
func AfterRevisionIn(vs ...int64) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIn(FieldAfterRevision, vs...))
}

// AfterRevisionNotIn applies the NotIn predicate on the "after_revision" field.
func AfterRevisionNotIn(vs ...int64) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotIn(FieldAfterRevision, vs...))
}

// AfterRevisionGT applies the GT predicate on the "after_revision" field.
func AfterRevisionGT(v int64) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGT(FieldAfterRevision, v))
}

// AfterRevisionGTE applies the GTE predicate on the "after_revision" field.
func AfterRevisionGTE(v int64) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGTE(FieldAfterRevision, v))
}

// AfterRevisionLT applies the LT predicate on the "after_revision" field.
func AfterRevisionLT(v int64) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLT(FieldAfterRevision, v))
}

// AfterRevisionLTE applies the LTE predicate on the "after_revision" field.
func AfterRevisionLTE(v int64) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLTE(FieldAfterRevision, v))
}

// AfterRevisionIsNil applies the IsNil predicate on the "after_revision" field.
func AfterRevisionIsNil() predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIsNull(FieldAfterRevision))
}

// AfterRevisionNotNil applies the NotNil predicate on the "after_revision" field.
func AfterRevisionNotNil() predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotNull(FieldAfterRevision))
}

// ClassificationEQ applies the EQ predicate on the "classification" field.
func ClassificationEQ(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldClassification, v))
}

// ClassificationNEQ applies the NEQ predicate on the "classification" field.
func ClassificationNEQ(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNEQ(FieldClassification, v))
}

// ClassificationIn applies the In predicate on the "classification" field.
func ClassificationIn(vs ...string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIn(FieldClassification, vs...))
}

// ClassificationNotIn applies the NotIn predicate on the "classification" field.
func ClassificationNotIn(vs ...string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotIn(FieldClassification, vs...))
}

// ClassificationGT applies the GT predicate on the "classification" field.
func ClassificationGT(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGT(FieldClassification, v))
}

// ClassificationGTE applies the GTE predicate on the "classification" field.
func ClassificationGTE(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGTE(FieldClassification, v))
}

// ClassificationLT applies the LT predicate on the "classification" field.
func ClassificationLT(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLT(FieldClassification, v))
}

// ClassificationLTE applies the LTE predicate on the "classification" field.
func ClassificationLTE(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLTE(FieldClassification, v))
}

// ClassificationContains applies the Contains predicate on the "classification" field.
func ClassificationContains(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldContains(FieldClassification, v))
}

// ClassificationHasPrefix applies the HasPrefix predicate on the "classification" field.
func ClassificationHasPrefix(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldHasPrefix(FieldClassification, v))
}

// ClassificationHasSuffix applies the HasSuffix predicate on the "classification" field.
func ClassificationHasSuffix(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldHasSuffix(FieldClassification, v))
}

// ClassificationIsNil applies the IsNil predicate on the "classification" field.
func ClassificationIsNil() predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIsNull(FieldClassification))
}

// ClassificationNotNil applies the NotNil predicate on the "classification" field.
func ClassificationNotNil() predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotNull(FieldClassification))
}

// ClassificationEqualFold applies the EqualFold predicate on the "classification" field.
func ClassificationEqualFold(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEqualFold(FieldClassification, v))
}

// ClassificationContainsFold applies the ContainsFold predicate on the "classification" field.
func ClassificationContainsFold(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldContainsFold(FieldClassification, v))
}

// PreviewIDEQ applies the EQ predicate on the "preview_id" field.
func PreviewIDEQ(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldPreviewID, v))
}

// PreviewIDNEQ applies the NEQ predicate on the "preview_id" field.
func PreviewIDNEQ(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNEQ(FieldPreviewID, v))
}

// PreviewIDIn applies the In predicate on the "preview_id" field.
func PreviewIDIn(vs ...string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIn(FieldPreviewID, vs...))
}

// PreviewIDNotIn applies the NotIn predicate on the "preview_id" field.
func PreviewIDNotIn(vs ...string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotIn(FieldPreviewID, vs...))
}

// PreviewIDGT applies the GT predicate on the "preview_id" field.
func PreviewIDGT(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGT(FieldPreviewID, v))
}

// PreviewIDGTE applies the GTE predicate on the "preview_id" field.
func PreviewIDGTE(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGTE(FieldPreviewID, v))
}

// PreviewIDLT applies the LT predicate on the "preview_id" field.
func PreviewIDLT(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLT(FieldPreviewID, v))
}

// PreviewIDLTE applies the LTE predicate on the "preview_id" field.
func PreviewIDLTE(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLTE(FieldPreviewID, v))
}

// PreviewIDContains applies the Contains predicate on the "preview_id" field.
func PreviewIDContains(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldContains(FieldPreviewID, v))
}

// PreviewIDHasPrefix applies the HasPrefix predicate on the "preview_id" field.
func PreviewIDHasPrefix(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldHasPrefix(FieldPreviewID, v))
}

// PreviewIDHasSuffix applies the HasSuffix predicate on the "preview_id" field.
func PreviewIDHasSuffix(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldHasSuffix(FieldPreviewID, v))
}

// PreviewIDIsNil applies the IsNil predicate on the "preview_id" field.
func PreviewIDIsNil() predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIsNull(FieldPreviewID))
}

// PreviewIDNotNil applies the NotNil predicate on the "preview_id" field.
func PreviewIDNotNil() predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotNull(FieldPreviewID))
}

// PreviewIDEqualFold applies the EqualFold predicate on the "preview_id" field.
func PreviewIDEqualFold(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEqualFold(FieldPreviewID, v))
}

// PreviewIDContainsFold applies the ContainsFold predicate on the "preview_id" field.
func PreviewIDContainsFold(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldContainsFold(FieldPreviewID, v))
}

// DraftHashEQ applies the EQ predicate on the "draft_hash" field.
func DraftHashEQ(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldDraftHash, v))
}

// DraftHashNEQ applies the NEQ predicate on the "draft_hash" field.
func DraftHashNEQ(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNEQ(FieldDraftHash, v))
}

// DraftHashIn applies the In predicate on the "draft_hash" field.
func DraftHashIn(vs ...string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIn(FieldDraftHash, vs...))
}

// DraftHashNotIn applies the NotIn predicate on the "draft_hash" field.
func DraftHashNotIn(vs ...string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotIn(FieldDraftHash, vs...))
}

// DraftHashGT applies the GT predicate on the "draft_hash" field.
func DraftHashGT(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGT(FieldDraftHash, v))
}

// DraftHashGTE applies the GTE predicate on the "draft_hash" field.
func DraftHashGTE(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGTE(FieldDraftHash, v))
}

// DraftHashLT applies the LT predicate on the "draft_hash" field.
func DraftHashLT(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLT(FieldDraftHash, v))
}

// DraftHashLTE applies the LTE predicate on the "draft_hash" field.
func DraftHashLTE(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLTE(FieldDraftHash, v))
}

// DraftHashContains applies the Contains predicate on the "draft_hash" field.
func DraftHashContains(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldContains(FieldDraftHash, v))
}

// DraftHashHasPrefix applies the HasPrefix predicate on the "draft_hash" field.
func DraftHashHasPrefix(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldHasPrefix(FieldDraftHash, v))
}

// DraftHashHasSuffix applies the HasSuffix predicate on the "draft_hash" field.
func DraftHashHasSuffix(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldHasSuffix(FieldDraftHash, v))
}

// DraftHashIsNil applies the IsNil predicate on the "draft_hash" field.
func DraftHashIsNil() predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIsNull(FieldDraftHash))
}

// DraftHashNotNil applies the NotNil predicate on the "draft_hash" field.
func DraftHashNotNil() predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotNull(FieldDraftHash))
}

// DraftHashEqualFold applies the EqualFold predicate on the "draft_hash" field.
func DraftHashEqualFold(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEqualFold(FieldDraftHash, v))
}

// DraftHashContainsFold applies the ContainsFold predicate on the "draft_hash" field.
func DraftHashContainsFold(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldContainsFold(FieldDraftHash, v))
}

// ImpactCountsJSONEQ applies the EQ predicate on the "impact_counts_json" field.
func ImpactCountsJSONEQ(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldImpactCountsJSON, v))
}

// ImpactCountsJSONNEQ applies the NEQ predicate on the "impact_counts_json" field.
func ImpactCountsJSONNEQ(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNEQ(FieldImpactCountsJSON, v))
}

// ImpactCountsJSONIn applies the In predicate on the "impact_counts_json" field.
func ImpactCountsJSONIn(vs ...string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIn(FieldImpactCountsJSON, vs...))
}

// ImpactCountsJSONNotIn applies the NotIn predicate on the "impact_counts_json" field.
func ImpactCountsJSONNotIn(vs ...string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotIn(FieldImpactCountsJSON, vs...))
}

// ImpactCountsJSONGT applies the GT predicate on the "impact_counts_json" field.
func ImpactCountsJSONGT(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGT(FieldImpactCountsJSON, v))
}

// ImpactCountsJSONGTE applies the GTE predicate on the "impact_counts_json" field.
func ImpactCountsJSONGTE(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGTE(FieldImpactCountsJSON, v))
}

// ImpactCountsJSONLT applies the LT predicate on the "impact_counts_json" field.
func ImpactCountsJSONLT(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLT(FieldImpactCountsJSON, v))
}

// ImpactCountsJSONLTE applies the LTE predicate on the "impact_counts_json" field.
func ImpactCountsJSONLTE(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLTE(FieldImpactCountsJSON, v))
}

// ImpactCountsJSONContains applies the Contains predicate on the "impact_counts_json" field.
func ImpactCountsJSONContains(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldContains(FieldImpactCountsJSON, v))
}

// ImpactCountsJSONHasPrefix applies the HasPrefix predicate on the "impact_counts_json" field.
func ImpactCountsJSONHasPrefix(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldHasPrefix(FieldImpactCountsJSON, v))
}

// ImpactCountsJSONHasSuffix applies the HasSuffix predicate on the "impact_counts_json" field.
func ImpactCountsJSONHasSuffix(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldHasSuffix(FieldImpactCountsJSON, v))
}

// ImpactCountsJSONIsNil applies the IsNil predicate on the "impact_counts_json" field.
func ImpactCountsJSONIsNil() predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIsNull(FieldImpactCountsJSON))
}

// ImpactCountsJSONNotNil applies the NotNil predicate on the "impact_counts_json" field.
func ImpactCountsJSONNotNil() predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotNull(FieldImpactCountsJSON))
}

// ImpactCountsJSONEqualFold applies the EqualFold predicate on the "impact_counts_json" field.
func ImpactCountsJSONEqualFold(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEqualFold(FieldImpactCountsJSON, v))
}

// ImpactCountsJSONContainsFold applies the ContainsFold predicate on the "impact_counts_json" field.
func ImpactCountsJSONContainsFold(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldContainsFold(FieldImpactCountsJSON, v))
}

// ChangedFieldsJSONEQ applies the EQ predicate on the "changed_fields_json" field.
func ChangedFieldsJSONEQ(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEQ(FieldChangedFieldsJSON, v))
}

// ChangedFieldsJSONNEQ applies the NEQ predicate on the "changed_fields_json" field.
func ChangedFieldsJSONNEQ(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNEQ(FieldChangedFieldsJSON, v))
}

// ChangedFieldsJSONIn applies the In predicate on the "changed_fields_json" field.
func ChangedFieldsJSONIn(vs ...string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIn(FieldChangedFieldsJSON, vs...))
}

// ChangedFieldsJSONNotIn applies the NotIn predicate on the "changed_fields_json" field.
func ChangedFieldsJSONNotIn(vs ...string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotIn(FieldChangedFieldsJSON, vs...))
}

// ChangedFieldsJSONGT applies the GT predicate on the "changed_fields_json" field.
func ChangedFieldsJSONGT(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGT(FieldChangedFieldsJSON, v))
}

// ChangedFieldsJSONGTE applies the GTE predicate on the "changed_fields_json" field.
func ChangedFieldsJSONGTE(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldGTE(FieldChangedFieldsJSON, v))
}

// ChangedFieldsJSONLT applies the LT predicate on the "changed_fields_json" field.
func ChangedFieldsJSONLT(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLT(FieldChangedFieldsJSON, v))
}

// ChangedFieldsJSONLTE applies the LTE predicate on the "changed_fields_json" field.
func ChangedFieldsJSONLTE(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldLTE(FieldChangedFieldsJSON, v))
}

// ChangedFieldsJSONContains applies the Contains predicate on the "changed_fields_json" field.
func ChangedFieldsJSONContains(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldContains(FieldChangedFieldsJSON, v))
}

// ChangedFieldsJSONHasPrefix applies the HasPrefix predicate on the "changed_fields_json" field.
func ChangedFieldsJSONHasPrefix(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldHasPrefix(FieldChangedFieldsJSON, v))
}

// ChangedFieldsJSONHasSuffix applies the HasSuffix predicate on the "changed_fields_json" field.
func ChangedFieldsJSONHasSuffix(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldHasSuffix(FieldChangedFieldsJSON, v))
}

// ChangedFieldsJSONIsNil applies the IsNil predicate on the "changed_fields_json" field.
func ChangedFieldsJSONIsNil() predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldIsNull(FieldChangedFieldsJSON))
}

// ChangedFieldsJSONNotNil applies the NotNil predicate on the "changed_fields_json" field.
func ChangedFieldsJSONNotNil() predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldNotNull(FieldChangedFieldsJSON))
}

// ChangedFieldsJSONEqualFold applies the EqualFold predicate on the "changed_fields_json" field.
func ChangedFieldsJSONEqualFold(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldEqualFold(FieldChangedFieldsJSON, v))
}

// ChangedFieldsJSONContainsFold applies the ContainsFold predicate on the "changed_fields_json" field.
func ChangedFieldsJSONContainsFold(v string) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.FieldContainsFold(FieldChangedFieldsJSON, v))
}

// HasConstraint applies the HasEdge predicate on the "constraint" edge.
func HasConstraint() predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ConstraintTable, ConstraintColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConstraintWith applies the HasEdge predicate on the "constraint" edge with a given conditions (other predicates).
func HasConstraintWith(preds ...predicate.AccessConstraint) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(func(s *sql.Selector) {
		step := newConstraintStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccessConstraintHistory) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccessConstraintHistory) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccessConstraintHistory) predicate.AccessConstraintHistory {
	return predicate.AccessConstraintHistory(sql.NotPredicates(p))
}
