// Code generated by ent, DO NOT EDIT.

package scheduledevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the scheduledevent type in the database.
	Label = "scheduled_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInitiatorPrincipalKind holds the string denoting the initiator_principal_kind field in the database.
	FieldInitiatorPrincipalKind = "initiator_principal_kind"
	// FieldInitiatorPrincipalID holds the string denoting the initiator_principal_id field in the database.
	FieldInitiatorPrincipalID = "initiator_principal_id"
	// FieldInitiatorCredentialKind holds the string denoting the initiator_credential_kind field in the database.
	FieldInitiatorCredentialKind = "initiator_credential_kind"
	// FieldInitiatorCredentialID holds the string denoting the initiator_credential_id field in the database.
	FieldInitiatorCredentialID = "initiator_credential_id"
	// FieldInitiatorCredentialSnapshot holds the string denoting the initiator_credential_snapshot field in the database.
	FieldInitiatorCredentialSnapshot = "initiator_credential_snapshot"
	// FieldAttributionVersion holds the string denoting the attribution_version field in the database.
	FieldAttributionVersion = "attribution_version"
	// FieldAuthorizationRevision holds the string denoting the authorization_revision field in the database.
	FieldAuthorizationRevision = "authorization_revision"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldFireAt holds the string denoting the fire_at field in the database.
	FieldFireAt = "fire_at"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldFiredAt holds the string denoting the fired_at field in the database.
	FieldFiredAt = "fired_at"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// FieldScheduleID holds the string denoting the schedule_id field in the database.
	FieldScheduleID = "schedule_id"
	// FieldCreated holds the string denoting the created field in the database.
	FieldCreated = "created"
	// Table holds the table name of the scheduledevent in the database.
	Table = "scheduled_events"
)

// Columns holds all SQL columns for scheduledevent fields.
var Columns = []string{
	FieldID,
	FieldInitiatorPrincipalKind,
	FieldInitiatorPrincipalID,
	FieldInitiatorCredentialKind,
	FieldInitiatorCredentialID,
	FieldInitiatorCredentialSnapshot,
	FieldAttributionVersion,
	FieldAuthorizationRevision,
	FieldProjectID,
	FieldEventType,
	FieldFireAt,
	FieldPayload,
	FieldStatus,
	FieldCreatedBy,
	FieldFiredAt,
	FieldError,
	FieldScheduleID,
	FieldCreated,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	EventTypeValidator func(string) error
	// PayloadValidator is a validator for the "payload" field. It is called by the builders before save.
	PayloadValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultCreated holds the default value on creation for the "created" field.
	DefaultCreated func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the ScheduledEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInitiatorPrincipalKind orders the results by the initiator_principal_kind field.
func ByInitiatorPrincipalKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInitiatorPrincipalKind, opts...).ToFunc()
}

// ByInitiatorPrincipalID orders the results by the initiator_principal_id field.
func ByInitiatorPrincipalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInitiatorPrincipalID, opts...).ToFunc()
}

// ByInitiatorCredentialKind orders the results by the initiator_credential_kind field.
func ByInitiatorCredentialKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInitiatorCredentialKind, opts...).ToFunc()
}

// ByInitiatorCredentialID orders the results by the initiator_credential_id field.
func ByInitiatorCredentialID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInitiatorCredentialID, opts...).ToFunc()
}

// ByInitiatorCredentialSnapshot orders the results by the initiator_credential_snapshot field.
func ByInitiatorCredentialSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInitiatorCredentialSnapshot, opts...).ToFunc()
}

// ByAttributionVersion orders the results by the attribution_version field.
func ByAttributionVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttributionVersion, opts...).ToFunc()
}

// ByAuthorizationRevision orders the results by the authorization_revision field.
func ByAuthorizationRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorizationRevision, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByFireAt orders the results by the fire_at field.
func ByFireAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFireAt, opts...).ToFunc()
}

// ByPayload orders the results by the payload field.
func ByPayload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayload, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByFiredAt orders the results by the fired_at field.
func ByFiredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFiredAt, opts...).ToFunc()
}

// ByError orders the results by the error field.
func ByError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldError, opts...).ToFunc()
}

// ByScheduleID orders the results by the schedule_id field.
func ByScheduleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScheduleID, opts...).ToFunc()
}

// ByCreated orders the results by the created field.
func ByCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreated, opts...).ToFunc()
}
