// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/accessconstraint"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/accessconstrainthistory"
	"github.com/google/uuid"
)

// AccessConstraintHistory is the model entity for the AccessConstraintHistory schema.
type AccessConstraintHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ConstraintID holds the value of the "constraint_id" field.
	ConstraintID uuid.UUID `json:"constraint_id,omitempty"`
	// OccurredAt holds the value of the "occurred_at" field.
	OccurredAt time.Time `json:"occurred_at,omitempty"`
	// Operation holds the value of the "operation" field.
	Operation string `json:"operation,omitempty"`
	// ActorKind holds the value of the "actor_kind" field.
	ActorKind *string `json:"actor_kind,omitempty"`
	// ActorID holds the value of the "actor_id" field.
	ActorID *string `json:"actor_id,omitempty"`
	// CorrelationID holds the value of the "correlation_id" field.
	CorrelationID *string `json:"correlation_id,omitempty"`
	// BatchOperationID holds the value of the "batch_operation_id" field.
	BatchOperationID *string `json:"batch_operation_id,omitempty"`
	// BeforeRevision holds the value of the "before_revision" field.
	BeforeRevision *int64 `json:"before_revision,omitempty"`
	// AfterRevision holds the value of the "after_revision" field.
	AfterRevision *int64 `json:"after_revision,omitempty"`
	// Classification holds the value of the "classification" field.
	Classification *string `json:"classification,omitempty"`
	// PreviewID holds the value of the "preview_id" field.
	PreviewID *string `json:"preview_id,omitempty"`
	// DraftHash holds the value of the "draft_hash" field.
	DraftHash *string `json:"draft_hash,omitempty"`
	// ImpactCountsJSON holds the value of the "impact_counts_json" field.
	ImpactCountsJSON *string `json:"impact_counts_json,omitempty"`
	// ChangedFieldsJSON holds the value of the "changed_fields_json" field.
	ChangedFieldsJSON *string `json:"changed_fields_json,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccessConstraintHistoryQuery when eager-loading is set.
	Edges        AccessConstraintHistoryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccessConstraintHistoryEdges holds the relations/edges for other nodes in the graph.
type AccessConstraintHistoryEdges struct {
	// Constraint holds the value of the constraint edge.
	Constraint *AccessConstraint `json:"constraint,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ConstraintOrErr returns the Constraint value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccessConstraintHistoryEdges) ConstraintOrErr() (*AccessConstraint, error) {
	if e.Constraint != nil {
		return e.Constraint, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: accessconstraint.Label}
	}
	return nil, &NotLoadedError{edge: "constraint"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccessConstraintHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accessconstrainthistory.FieldBeforeRevision, accessconstrainthistory.FieldAfterRevision:
			values[i] = new(sql.NullInt64)
		case accessconstrainthistory.FieldID, accessconstrainthistory.FieldOperation, accessconstrainthistory.FieldActorKind, accessconstrainthistory.FieldActorID, accessconstrainthistory.FieldCorrelationID, accessconstrainthistory.FieldBatchOperationID, accessconstrainthistory.FieldClassification, accessconstrainthistory.FieldPreviewID, accessconstrainthistory.FieldDraftHash, accessconstrainthistory.FieldImpactCountsJSON, accessconstrainthistory.FieldChangedFieldsJSON:
			values[i] = new(sql.NullString)
		case accessconstrainthistory.FieldOccurredAt:
			values[i] = new(sql.NullTime)
		case accessconstrainthistory.FieldConstraintID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccessConstraintHistory fields.
func (_m *AccessConstraintHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accessconstrainthistory.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case accessconstrainthistory.FieldConstraintID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field constraint_id", values[i])
			} else if value != nil {
				_m.ConstraintID = *value
			}
		case accessconstrainthistory.FieldOccurredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field occurred_at", values[i])
			} else if value.Valid {
				_m.OccurredAt = value.Time
			}
		case accessconstrainthistory.FieldOperation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation", values[i])
			} else if value.Valid {
				_m.Operation = value.String
			}
		case accessconstrainthistory.FieldActorKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_kind", values[i])
			} else if value.Valid {
				_m.ActorKind = new(string)
				*_m.ActorKind = value.String
			}
		case accessconstrainthistory.FieldActorID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_id", values[i])
			} else if value.Valid {
				_m.ActorID = new(string)
				*_m.ActorID = value.String
			}
		case accessconstrainthistory.FieldCorrelationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field correlation_id", values[i])
			} else if value.Valid {
				_m.CorrelationID = new(string)
				*_m.CorrelationID = value.String
			}
		case accessconstrainthistory.FieldBatchOperationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field batch_operation_id", values[i])
			} else if value.Valid {
				_m.BatchOperationID = new(string)
				*_m.BatchOperationID = value.String
			}
		case accessconstrainthistory.FieldBeforeRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field before_revision", values[i])
			} else if value.Valid {
				_m.BeforeRevision = new(int64)
				*_m.BeforeRevision = value.Int64
			}
		case accessconstrainthistory.FieldAfterRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field after_revision", values[i])
			} else if value.Valid {
				_m.AfterRevision = new(int64)
				*_m.AfterRevision = value.Int64
			}
		case accessconstrainthistory.FieldClassification:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field classification", values[i])
			} else if value.Valid {
				_m.Classification = new(string)
				*_m.Classification = value.String
			}
		case accessconstrainthistory.FieldPreviewID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field preview_id", values[i])
			} else if value.Valid {
				_m.PreviewID = new(string)
				*_m.PreviewID = value.String
			}
		case accessconstrainthistory.FieldDraftHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field draft_hash", values[i])
			} else if value.Valid {
				_m.DraftHash = new(string)
				*_m.DraftHash = value.String
			}
		case accessconstrainthistory.FieldImpactCountsJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field impact_counts_json", values[i])
			} else if value.Valid {
				_m.ImpactCountsJSON = new(string)
				*_m.ImpactCountsJSON = value.String
			}
		case accessconstrainthistory.FieldChangedFieldsJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field changed_fields_json", values[i])
			} else if value.Valid {
				_m.ChangedFieldsJSON = new(string)
				*_m.ChangedFieldsJSON = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccessConstraintHistory.
// This includes values selected through modifiers, order, etc.
func (_m *AccessConstraintHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryConstraint queries the "constraint" edge of the AccessConstraintHistory entity.
func (_m *AccessConstraintHistory) QueryConstraint() *AccessConstraintQuery {
	return NewAccessConstraintHistoryClient(_m.config).QueryConstraint(_m)
}

// Update returns a builder for updating this AccessConstraintHistory.
// Note that you need to call AccessConstraintHistory.Unwrap() before calling this method if this AccessConstraintHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccessConstraintHistory) Update() *AccessConstraintHistoryUpdateOne {
	return NewAccessConstraintHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccessConstraintHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccessConstraintHistory) Unwrap() *AccessConstraintHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccessConstraintHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccessConstraintHistory) String() string {
	var builder strings.Builder
	builder.WriteString("AccessConstraintHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("constraint_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConstraintID))
	builder.WriteString(", ")
	builder.WriteString("occurred_at=")
	builder.WriteString(_m.OccurredAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("operation=")
	builder.WriteString(_m.Operation)
	builder.WriteString(", ")
	if v := _m.ActorKind; v != nil {
		builder.WriteString("actor_kind=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ActorID; v != nil {
		builder.WriteString("actor_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CorrelationID; v != nil {
		builder.WriteString("correlation_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.BatchOperationID; v != nil {
		builder.WriteString("batch_operation_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.BeforeRevision; v != nil {
		builder.WriteString("before_revision=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AfterRevision; v != nil {
		builder.WriteString("after_revision=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Classification; v != nil {
		builder.WriteString("classification=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PreviewID; v != nil {
		builder.WriteString("preview_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DraftHash; v != nil {
		builder.WriteString("draft_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ImpactCountsJSON; v != nil {
		builder.WriteString("impact_counts_json=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ChangedFieldsJSON; v != nil {
		builder.WriteString("changed_fields_json=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// AccessConstraintHistories is a parsable slice of AccessConstraintHistory.
type AccessConstraintHistories []*AccessConstraintHistory
