// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/accessconstraint"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/accessconstrainthistory"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/google/uuid"
)

// AccessConstraintHistoryQuery is the builder for querying AccessConstraintHistory entities.
type AccessConstraintHistoryQuery struct {
	config
	ctx            *QueryContext
	order          []accessconstrainthistory.OrderOption
	inters         []Interceptor
	predicates     []predicate.AccessConstraintHistory
	withConstraint *AccessConstraintQuery
	modifiers      []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AccessConstraintHistoryQuery builder.
func (_q *AccessConstraintHistoryQuery) Where(ps ...predicate.AccessConstraintHistory) *AccessConstraintHistoryQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AccessConstraintHistoryQuery) Limit(limit int) *AccessConstraintHistoryQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AccessConstraintHistoryQuery) Offset(offset int) *AccessConstraintHistoryQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AccessConstraintHistoryQuery) Unique(unique bool) *AccessConstraintHistoryQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AccessConstraintHistoryQuery) Order(o ...accessconstrainthistory.OrderOption) *AccessConstraintHistoryQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryConstraint chains the current query on the "constraint" edge.
func (_q *AccessConstraintHistoryQuery) QueryConstraint() *AccessConstraintQuery {
	query := (&AccessConstraintClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(accessconstrainthistory.Table, accessconstrainthistory.FieldID, selector),
			sqlgraph.To(accessconstraint.Table, accessconstraint.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, accessconstrainthistory.ConstraintTable, accessconstrainthistory.ConstraintColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AccessConstraintHistory entity from the query.
// Returns a *NotFoundError when no AccessConstraintHistory was found.
func (_q *AccessConstraintHistoryQuery) First(ctx context.Context) (*AccessConstraintHistory, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{accessconstrainthistory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AccessConstraintHistoryQuery) FirstX(ctx context.Context) *AccessConstraintHistory {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AccessConstraintHistory ID from the query.
// Returns a *NotFoundError when no AccessConstraintHistory ID was found.
func (_q *AccessConstraintHistoryQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{accessconstrainthistory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AccessConstraintHistoryQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AccessConstraintHistory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AccessConstraintHistory entity is found.
// Returns a *NotFoundError when no AccessConstraintHistory entities are found.
func (_q *AccessConstraintHistoryQuery) Only(ctx context.Context) (*AccessConstraintHistory, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{accessconstrainthistory.Label}
	default:
		return nil, &NotSingularError{accessconstrainthistory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AccessConstraintHistoryQuery) OnlyX(ctx context.Context) *AccessConstraintHistory {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AccessConstraintHistory ID in the query.
// Returns a *NotSingularError when more than one AccessConstraintHistory ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AccessConstraintHistoryQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{accessconstrainthistory.Label}
	default:
		err = &NotSingularError{accessconstrainthistory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AccessConstraintHistoryQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AccessConstraintHistories.
func (_q *AccessConstraintHistoryQuery) All(ctx context.Context) ([]*AccessConstraintHistory, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AccessConstraintHistory, *AccessConstraintHistoryQuery]()
	return withInterceptors[[]*AccessConstraintHistory](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AccessConstraintHistoryQuery) AllX(ctx context.Context) []*AccessConstraintHistory {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AccessConstraintHistory IDs.
func (_q *AccessConstraintHistoryQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(accessconstrainthistory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AccessConstraintHistoryQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AccessConstraintHistoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AccessConstraintHistoryQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AccessConstraintHistoryQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AccessConstraintHistoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AccessConstraintHistoryQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AccessConstraintHistoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AccessConstraintHistoryQuery) Clone() *AccessConstraintHistoryQuery {
	if _q == nil {
		return nil
	}
	return &AccessConstraintHistoryQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]accessconstrainthistory.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.AccessConstraintHistory{}, _q.predicates...),
		withConstraint: _q.withConstraint.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithConstraint tells the query-builder to eager-load the nodes that are connected to
// the "constraint" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AccessConstraintHistoryQuery) WithConstraint(opts ...func(*AccessConstraintQuery)) *AccessConstraintHistoryQuery {
	query := (&AccessConstraintClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withConstraint = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ConstraintID uuid.UUID `json:"constraint_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AccessConstraintHistory.Query().
//		GroupBy(accessconstrainthistory.FieldConstraintID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AccessConstraintHistoryQuery) GroupBy(field string, fields ...string) *AccessConstraintHistoryGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AccessConstraintHistoryGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = accessconstrainthistory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ConstraintID uuid.UUID `json:"constraint_id,omitempty"`
//	}
//
//	client.AccessConstraintHistory.Query().
//		Select(accessconstrainthistory.FieldConstraintID).
//		Scan(ctx, &v)
func (_q *AccessConstraintHistoryQuery) Select(fields ...string) *AccessConstraintHistorySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AccessConstraintHistorySelect{AccessConstraintHistoryQuery: _q}
	sbuild.label = accessconstrainthistory.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AccessConstraintHistorySelect configured with the given aggregations.
func (_q *AccessConstraintHistoryQuery) Aggregate(fns ...AggregateFunc) *AccessConstraintHistorySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AccessConstraintHistoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !accessconstrainthistory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AccessConstraintHistoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AccessConstraintHistory, error) {
	var (
		nodes       = []*AccessConstraintHistory{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withConstraint != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AccessConstraintHistory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AccessConstraintHistory{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withConstraint; query != nil {
		if err := _q.loadConstraint(ctx, query, nodes, nil,
			func(n *AccessConstraintHistory, e *AccessConstraint) { n.Edges.Constraint = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AccessConstraintHistoryQuery) loadConstraint(ctx context.Context, query *AccessConstraintQuery, nodes []*AccessConstraintHistory, init func(*AccessConstraintHistory), assign func(*AccessConstraintHistory, *AccessConstraint)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*AccessConstraintHistory)
	for i := range nodes {
		fk := nodes[i].ConstraintID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(accessconstraint.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "constraint_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *AccessConstraintHistoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AccessConstraintHistoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(accessconstrainthistory.Table, accessconstrainthistory.Columns, sqlgraph.NewFieldSpec(accessconstrainthistory.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accessconstrainthistory.FieldID)
		for i := range fields {
			if fields[i] != accessconstrainthistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withConstraint != nil {
			_spec.Node.AddColumnOnce(accessconstrainthistory.FieldConstraintID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AccessConstraintHistoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(accessconstrainthistory.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = accessconstrainthistory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *AccessConstraintHistoryQuery) ForUpdate(opts ...sql.LockOption) *AccessConstraintHistoryQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *AccessConstraintHistoryQuery) ForShare(opts ...sql.LockOption) *AccessConstraintHistoryQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// AccessConstraintHistoryGroupBy is the group-by builder for AccessConstraintHistory entities.
type AccessConstraintHistoryGroupBy struct {
	selector
	build *AccessConstraintHistoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AccessConstraintHistoryGroupBy) Aggregate(fns ...AggregateFunc) *AccessConstraintHistoryGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AccessConstraintHistoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AccessConstraintHistoryQuery, *AccessConstraintHistoryGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AccessConstraintHistoryGroupBy) sqlScan(ctx context.Context, root *AccessConstraintHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AccessConstraintHistorySelect is the builder for selecting fields of AccessConstraintHistory entities.
type AccessConstraintHistorySelect struct {
	*AccessConstraintHistoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AccessConstraintHistorySelect) Aggregate(fns ...AggregateFunc) *AccessConstraintHistorySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AccessConstraintHistorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AccessConstraintHistoryQuery, *AccessConstraintHistorySelect](ctx, _s.AccessConstraintHistoryQuery, _s, _s.inters, v)
}

func (_s *AccessConstraintHistorySelect) sqlScan(ctx context.Context, root *AccessConstraintHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
