// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/accessconstrainthistory"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
)

// AccessConstraintHistoryDelete is the builder for deleting a AccessConstraintHistory entity.
type AccessConstraintHistoryDelete struct {
	config
	hooks    []Hook
	mutation *AccessConstraintHistoryMutation
}

// Where appends a list predicates to the AccessConstraintHistoryDelete builder.
func (_d *AccessConstraintHistoryDelete) Where(ps ...predicate.AccessConstraintHistory) *AccessConstraintHistoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccessConstraintHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccessConstraintHistoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccessConstraintHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accessconstrainthistory.Table, sqlgraph.NewFieldSpec(accessconstrainthistory.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccessConstraintHistoryDeleteOne is the builder for deleting a single AccessConstraintHistory entity.
type AccessConstraintHistoryDeleteOne struct {
	_d *AccessConstraintHistoryDelete
}

// Where appends a list predicates to the AccessConstraintHistoryDelete builder.
func (_d *AccessConstraintHistoryDeleteOne) Where(ps ...predicate.AccessConstraintHistory) *AccessConstraintHistoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccessConstraintHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accessconstrainthistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccessConstraintHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
