// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/accessconstraint"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/accessconstrainthistory"
	"github.com/google/uuid"
)

// AccessConstraintHistoryCreate is the builder for creating a AccessConstraintHistory entity.
type AccessConstraintHistoryCreate struct {
	config
	mutation *AccessConstraintHistoryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetConstraintID sets the "constraint_id" field.
func (_c *AccessConstraintHistoryCreate) SetConstraintID(v uuid.UUID) *AccessConstraintHistoryCreate {
	_c.mutation.SetConstraintID(v)
	return _c
}

// SetOccurredAt sets the "occurred_at" field.
func (_c *AccessConstraintHistoryCreate) SetOccurredAt(v time.Time) *AccessConstraintHistoryCreate {
	_c.mutation.SetOccurredAt(v)
	return _c
}

// SetOperation sets the "operation" field.
func (_c *AccessConstraintHistoryCreate) SetOperation(v string) *AccessConstraintHistoryCreate {
	_c.mutation.SetOperation(v)
	return _c
}

// SetActorKind sets the "actor_kind" field.
func (_c *AccessConstraintHistoryCreate) SetActorKind(v string) *AccessConstraintHistoryCreate {
	_c.mutation.SetActorKind(v)
	return _c
}

// SetNillableActorKind sets the "actor_kind" field if the given value is not nil.
func (_c *AccessConstraintHistoryCreate) SetNillableActorKind(v *string) *AccessConstraintHistoryCreate {
	if v != nil {
		_c.SetActorKind(*v)
	}
	return _c
}

// SetActorID sets the "actor_id" field.
func (_c *AccessConstraintHistoryCreate) SetActorID(v string) *AccessConstraintHistoryCreate {
	_c.mutation.SetActorID(v)
	return _c
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_c *AccessConstraintHistoryCreate) SetNillableActorID(v *string) *AccessConstraintHistoryCreate {
	if v != nil {
		_c.SetActorID(*v)
	}
	return _c
}

// SetCorrelationID sets the "correlation_id" field.
func (_c *AccessConstraintHistoryCreate) SetCorrelationID(v string) *AccessConstraintHistoryCreate {
	_c.mutation.SetCorrelationID(v)
	return _c
}

// SetNillableCorrelationID sets the "correlation_id" field if the given value is not nil.
func (_c *AccessConstraintHistoryCreate) SetNillableCorrelationID(v *string) *AccessConstraintHistoryCreate {
	if v != nil {
		_c.SetCorrelationID(*v)
	}
	return _c
}

// SetBatchOperationID sets the "batch_operation_id" field.
func (_c *AccessConstraintHistoryCreate) SetBatchOperationID(v string) *AccessConstraintHistoryCreate {
	_c.mutation.SetBatchOperationID(v)
	return _c
}

// SetNillableBatchOperationID sets the "batch_operation_id" field if the given value is not nil.
func (_c *AccessConstraintHistoryCreate) SetNillableBatchOperationID(v *string) *AccessConstraintHistoryCreate {
	if v != nil {
		_c.SetBatchOperationID(*v)
	}
	return _c
}

// SetBeforeRevision sets the "before_revision" field.
func (_c *AccessConstraintHistoryCreate) SetBeforeRevision(v int64) *AccessConstraintHistoryCreate {
	_c.mutation.SetBeforeRevision(v)
	return _c
}

// SetNillableBeforeRevision sets the "before_revision" field if the given value is not nil.
func (_c *AccessConstraintHistoryCreate) SetNillableBeforeRevision(v *int64) *AccessConstraintHistoryCreate {
	if v != nil {
		_c.SetBeforeRevision(*v)
	}
	return _c
}

// SetAfterRevision sets the "after_revision" field.
func (_c *AccessConstraintHistoryCreate) SetAfterRevision(v int64) *AccessConstraintHistoryCreate {
	_c.mutation.SetAfterRevision(v)
	return _c
}

// SetNillableAfterRevision sets the "after_revision" field if the given value is not nil.
func (_c *AccessConstraintHistoryCreate) SetNillableAfterRevision(v *int64) *AccessConstraintHistoryCreate {
	if v != nil {
		_c.SetAfterRevision(*v)
	}
	return _c
}

// SetClassification sets the "classification" field.
func (_c *AccessConstraintHistoryCreate) SetClassification(v string) *AccessConstraintHistoryCreate {
	_c.mutation.SetClassification(v)
	return _c
}

// SetNillableClassification sets the "classification" field if the given value is not nil.
func (_c *AccessConstraintHistoryCreate) SetNillableClassification(v *string) *AccessConstraintHistoryCreate {
	if v != nil {
		_c.SetClassification(*v)
	}
	return _c
}

// SetPreviewID sets the "preview_id" field.
func (_c *AccessConstraintHistoryCreate) SetPreviewID(v string) *AccessConstraintHistoryCreate {
	_c.mutation.SetPreviewID(v)
	return _c
}

// SetNillablePreviewID sets the "preview_id" field if the given value is not nil.
func (_c *AccessConstraintHistoryCreate) SetNillablePreviewID(v *string) *AccessConstraintHistoryCreate {
	if v != nil {
		_c.SetPreviewID(*v)
	}
	return _c
}

// SetDraftHash sets the "draft_hash" field.
func (_c *AccessConstraintHistoryCreate) SetDraftHash(v string) *AccessConstraintHistoryCreate {
	_c.mutation.SetDraftHash(v)
	return _c
}

// SetNillableDraftHash sets the "draft_hash" field if the given value is not nil.
func (_c *AccessConstraintHistoryCreate) SetNillableDraftHash(v *string) *AccessConstraintHistoryCreate {
	if v != nil {
		_c.SetDraftHash(*v)
	}
	return _c
}

// SetImpactCountsJSON sets the "impact_counts_json" field.
func (_c *AccessConstraintHistoryCreate) SetImpactCountsJSON(v string) *AccessConstraintHistoryCreate {
	_c.mutation.SetImpactCountsJSON(v)
	return _c
}

// SetNillableImpactCountsJSON sets the "impact_counts_json" field if the given value is not nil.
func (_c *AccessConstraintHistoryCreate) SetNillableImpactCountsJSON(v *string) *AccessConstraintHistoryCreate {
	if v != nil {
		_c.SetImpactCountsJSON(*v)
	}
	return _c
}

// SetChangedFieldsJSON sets the "changed_fields_json" field.
func (_c *AccessConstraintHistoryCreate) SetChangedFieldsJSON(v string) *AccessConstraintHistoryCreate {
	_c.mutation.SetChangedFieldsJSON(v)
	return _c
}

// SetNillableChangedFieldsJSON sets the "changed_fields_json" field if the given value is not nil.
func (_c *AccessConstraintHistoryCreate) SetNillableChangedFieldsJSON(v *string) *AccessConstraintHistoryCreate {
	if v != nil {
		_c.SetChangedFieldsJSON(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AccessConstraintHistoryCreate) SetID(v string) *AccessConstraintHistoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetConstraint sets the "constraint" edge to the AccessConstraint entity.
func (_c *AccessConstraintHistoryCreate) SetConstraint(v *AccessConstraint) *AccessConstraintHistoryCreate {
	return _c.SetConstraintID(v.ID)
}

// Mutation returns the AccessConstraintHistoryMutation object of the builder.
func (_c *AccessConstraintHistoryCreate) Mutation() *AccessConstraintHistoryMutation {
	return _c.mutation
}

// Save creates the AccessConstraintHistory in the database.
func (_c *AccessConstraintHistoryCreate) Save(ctx context.Context) (*AccessConstraintHistory, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccessConstraintHistoryCreate) SaveX(ctx context.Context) *AccessConstraintHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessConstraintHistoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessConstraintHistoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccessConstraintHistoryCreate) check() error {
	if _, ok := _c.mutation.ConstraintID(); !ok {
		return &ValidationError{Name: "constraint_id", err: errors.New(`ent: missing required field "AccessConstraintHistory.constraint_id"`)}
	}
	if _, ok := _c.mutation.OccurredAt(); !ok {
		return &ValidationError{Name: "occurred_at", err: errors.New(`ent: missing required field "AccessConstraintHistory.occurred_at"`)}
	}
	if _, ok := _c.mutation.Operation(); !ok {
		return &ValidationError{Name: "operation", err: errors.New(`ent: missing required field "AccessConstraintHistory.operation"`)}
	}
	if v, ok := _c.mutation.Operation(); ok {
		if err := accessconstrainthistory.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "AccessConstraintHistory.operation": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := accessconstrainthistory.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "AccessConstraintHistory.id": %w`, err)}
		}
	}
	if len(_c.mutation.ConstraintIDs()) == 0 {
		return &ValidationError{Name: "constraint", err: errors.New(`ent: missing required edge "AccessConstraintHistory.constraint"`)}
	}
	return nil
}

func (_c *AccessConstraintHistoryCreate) sqlSave(ctx context.Context) (*AccessConstraintHistory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AccessConstraintHistory.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccessConstraintHistoryCreate) createSpec() (*AccessConstraintHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &AccessConstraintHistory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accessconstrainthistory.Table, sqlgraph.NewFieldSpec(accessconstrainthistory.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.OccurredAt(); ok {
		_spec.SetField(accessconstrainthistory.FieldOccurredAt, field.TypeTime, value)
		_node.OccurredAt = value
	}
	if value, ok := _c.mutation.Operation(); ok {
		_spec.SetField(accessconstrainthistory.FieldOperation, field.TypeString, value)
		_node.Operation = value
	}
	if value, ok := _c.mutation.ActorKind(); ok {
		_spec.SetField(accessconstrainthistory.FieldActorKind, field.TypeString, value)
		_node.ActorKind = &value
	}
	if value, ok := _c.mutation.ActorID(); ok {
		_spec.SetField(accessconstrainthistory.FieldActorID, field.TypeString, value)
		_node.ActorID = &value
	}
	if value, ok := _c.mutation.CorrelationID(); ok {
		_spec.SetField(accessconstrainthistory.FieldCorrelationID, field.TypeString, value)
		_node.CorrelationID = &value
	}
	if value, ok := _c.mutation.BatchOperationID(); ok {
		_spec.SetField(accessconstrainthistory.FieldBatchOperationID, field.TypeString, value)
		_node.BatchOperationID = &value
	}
	if value, ok := _c.mutation.BeforeRevision(); ok {
		_spec.SetField(accessconstrainthistory.FieldBeforeRevision, field.TypeInt64, value)
		_node.BeforeRevision = &value
	}
	if value, ok := _c.mutation.AfterRevision(); ok {
		_spec.SetField(accessconstrainthistory.FieldAfterRevision, field.TypeInt64, value)
		_node.AfterRevision = &value
	}
	if value, ok := _c.mutation.Classification(); ok {
		_spec.SetField(accessconstrainthistory.FieldClassification, field.TypeString, value)
		_node.Classification = &value
	}
	if value, ok := _c.mutation.PreviewID(); ok {
		_spec.SetField(accessconstrainthistory.FieldPreviewID, field.TypeString, value)
		_node.PreviewID = &value
	}
	if value, ok := _c.mutation.DraftHash(); ok {
		_spec.SetField(accessconstrainthistory.FieldDraftHash, field.TypeString, value)
		_node.DraftHash = &value
	}
	if value, ok := _c.mutation.ImpactCountsJSON(); ok {
		_spec.SetField(accessconstrainthistory.FieldImpactCountsJSON, field.TypeString, value)
		_node.ImpactCountsJSON = &value
	}
	if value, ok := _c.mutation.ChangedFieldsJSON(); ok {
		_spec.SetField(accessconstrainthistory.FieldChangedFieldsJSON, field.TypeString, value)
		_node.ChangedFieldsJSON = &value
	}
	if nodes := _c.mutation.ConstraintIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accessconstrainthistory.ConstraintTable,
			Columns: []string{accessconstrainthistory.ConstraintColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accessconstraint.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ConstraintID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccessConstraintHistory.Create().
//		SetConstraintID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccessConstraintHistoryUpsert) {
//			SetConstraintID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccessConstraintHistoryCreate) OnConflict(opts ...sql.ConflictOption) *AccessConstraintHistoryUpsertOne {
	_c.conflict = opts
	return &AccessConstraintHistoryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccessConstraintHistory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccessConstraintHistoryCreate) OnConflictColumns(columns ...string) *AccessConstraintHistoryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccessConstraintHistoryUpsertOne{
		create: _c,
	}
}

type (
	// AccessConstraintHistoryUpsertOne is the builder for "upsert"-ing
	//  one AccessConstraintHistory node.
	AccessConstraintHistoryUpsertOne struct {
		create *AccessConstraintHistoryCreate
	}

	// AccessConstraintHistoryUpsert is the "OnConflict" setter.
	AccessConstraintHistoryUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AccessConstraintHistory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(accessconstrainthistory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AccessConstraintHistoryUpsertOne) UpdateNewValues() *AccessConstraintHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(accessconstrainthistory.FieldID)
		}
		if _, exists := u.create.mutation.ConstraintID(); exists {
			s.SetIgnore(accessconstrainthistory.FieldConstraintID)
		}
		if _, exists := u.create.mutation.OccurredAt(); exists {
			s.SetIgnore(accessconstrainthistory.FieldOccurredAt)
		}
		if _, exists := u.create.mutation.Operation(); exists {
			s.SetIgnore(accessconstrainthistory.FieldOperation)
		}
		if _, exists := u.create.mutation.ActorKind(); exists {
			s.SetIgnore(accessconstrainthistory.FieldActorKind)
		}
		if _, exists := u.create.mutation.ActorID(); exists {
			s.SetIgnore(accessconstrainthistory.FieldActorID)
		}
		if _, exists := u.create.mutation.CorrelationID(); exists {
			s.SetIgnore(accessconstrainthistory.FieldCorrelationID)
		}
		if _, exists := u.create.mutation.BatchOperationID(); exists {
			s.SetIgnore(accessconstrainthistory.FieldBatchOperationID)
		}
		if _, exists := u.create.mutation.BeforeRevision(); exists {
			s.SetIgnore(accessconstrainthistory.FieldBeforeRevision)
		}
		if _, exists := u.create.mutation.AfterRevision(); exists {
			s.SetIgnore(accessconstrainthistory.FieldAfterRevision)
		}
		if _, exists := u.create.mutation.Classification(); exists {
			s.SetIgnore(accessconstrainthistory.FieldClassification)
		}
		if _, exists := u.create.mutation.PreviewID(); exists {
			s.SetIgnore(accessconstrainthistory.FieldPreviewID)
		}
		if _, exists := u.create.mutation.DraftHash(); exists {
			s.SetIgnore(accessconstrainthistory.FieldDraftHash)
		}
		if _, exists := u.create.mutation.ImpactCountsJSON(); exists {
			s.SetIgnore(accessconstrainthistory.FieldImpactCountsJSON)
		}
		if _, exists := u.create.mutation.ChangedFieldsJSON(); exists {
			s.SetIgnore(accessconstrainthistory.FieldChangedFieldsJSON)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccessConstraintHistory.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccessConstraintHistoryUpsertOne) Ignore() *AccessConstraintHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccessConstraintHistoryUpsertOne) DoNothing() *AccessConstraintHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccessConstraintHistoryCreate.OnConflict
// documentation for more info.
func (u *AccessConstraintHistoryUpsertOne) Update(set func(*AccessConstraintHistoryUpsert)) *AccessConstraintHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccessConstraintHistoryUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *AccessConstraintHistoryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccessConstraintHistoryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccessConstraintHistoryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccessConstraintHistoryUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AccessConstraintHistoryUpsertOne.ID is not supported by MySQL driver. Use AccessConstraintHistoryUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccessConstraintHistoryUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccessConstraintHistoryCreateBulk is the builder for creating many AccessConstraintHistory entities in bulk.
type AccessConstraintHistoryCreateBulk struct {
	config
	err      error
	builders []*AccessConstraintHistoryCreate
	conflict []sql.ConflictOption
}

// Save creates the AccessConstraintHistory entities in the database.
func (_c *AccessConstraintHistoryCreateBulk) Save(ctx context.Context) ([]*AccessConstraintHistory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccessConstraintHistory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccessConstraintHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccessConstraintHistoryCreateBulk) SaveX(ctx context.Context) []*AccessConstraintHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessConstraintHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessConstraintHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccessConstraintHistory.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccessConstraintHistoryUpsert) {
//			SetConstraintID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccessConstraintHistoryCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccessConstraintHistoryUpsertBulk {
	_c.conflict = opts
	return &AccessConstraintHistoryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccessConstraintHistory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccessConstraintHistoryCreateBulk) OnConflictColumns(columns ...string) *AccessConstraintHistoryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccessConstraintHistoryUpsertBulk{
		create: _c,
	}
}

// AccessConstraintHistoryUpsertBulk is the builder for "upsert"-ing
// a bulk of AccessConstraintHistory nodes.
type AccessConstraintHistoryUpsertBulk struct {
	create *AccessConstraintHistoryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccessConstraintHistory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(accessconstrainthistory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AccessConstraintHistoryUpsertBulk) UpdateNewValues() *AccessConstraintHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(accessconstrainthistory.FieldID)
			}
			if _, exists := b.mutation.ConstraintID(); exists {
				s.SetIgnore(accessconstrainthistory.FieldConstraintID)
			}
			if _, exists := b.mutation.OccurredAt(); exists {
				s.SetIgnore(accessconstrainthistory.FieldOccurredAt)
			}
			if _, exists := b.mutation.Operation(); exists {
				s.SetIgnore(accessconstrainthistory.FieldOperation)
			}
			if _, exists := b.mutation.ActorKind(); exists {
				s.SetIgnore(accessconstrainthistory.FieldActorKind)
			}
			if _, exists := b.mutation.ActorID(); exists {
				s.SetIgnore(accessconstrainthistory.FieldActorID)
			}
			if _, exists := b.mutation.CorrelationID(); exists {
				s.SetIgnore(accessconstrainthistory.FieldCorrelationID)
			}
			if _, exists := b.mutation.BatchOperationID(); exists {
				s.SetIgnore(accessconstrainthistory.FieldBatchOperationID)
			}
			if _, exists := b.mutation.BeforeRevision(); exists {
				s.SetIgnore(accessconstrainthistory.FieldBeforeRevision)
			}
			if _, exists := b.mutation.AfterRevision(); exists {
				s.SetIgnore(accessconstrainthistory.FieldAfterRevision)
			}
			if _, exists := b.mutation.Classification(); exists {
				s.SetIgnore(accessconstrainthistory.FieldClassification)
			}
			if _, exists := b.mutation.PreviewID(); exists {
				s.SetIgnore(accessconstrainthistory.FieldPreviewID)
			}
			if _, exists := b.mutation.DraftHash(); exists {
				s.SetIgnore(accessconstrainthistory.FieldDraftHash)
			}
			if _, exists := b.mutation.ImpactCountsJSON(); exists {
				s.SetIgnore(accessconstrainthistory.FieldImpactCountsJSON)
			}
			if _, exists := b.mutation.ChangedFieldsJSON(); exists {
				s.SetIgnore(accessconstrainthistory.FieldChangedFieldsJSON)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccessConstraintHistory.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccessConstraintHistoryUpsertBulk) Ignore() *AccessConstraintHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccessConstraintHistoryUpsertBulk) DoNothing() *AccessConstraintHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccessConstraintHistoryCreateBulk.OnConflict
// documentation for more info.
func (u *AccessConstraintHistoryUpsertBulk) Update(set func(*AccessConstraintHistoryUpsert)) *AccessConstraintHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccessConstraintHistoryUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *AccessConstraintHistoryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccessConstraintHistoryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccessConstraintHistoryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccessConstraintHistoryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
