// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/accessconstrainthistory"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
)

// AccessConstraintHistoryUpdate is the builder for updating AccessConstraintHistory entities.
type AccessConstraintHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *AccessConstraintHistoryMutation
}

// Where appends a list predicates to the AccessConstraintHistoryUpdate builder.
func (_u *AccessConstraintHistoryUpdate) Where(ps ...predicate.AccessConstraintHistory) *AccessConstraintHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the AccessConstraintHistoryMutation object of the builder.
func (_u *AccessConstraintHistoryUpdate) Mutation() *AccessConstraintHistoryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccessConstraintHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccessConstraintHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccessConstraintHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccessConstraintHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccessConstraintHistoryUpdate) check() error {
	if _u.mutation.ConstraintCleared() && len(_u.mutation.ConstraintIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccessConstraintHistory.constraint"`)
	}
	return nil
}

func (_u *AccessConstraintHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accessconstrainthistory.Table, accessconstrainthistory.Columns, sqlgraph.NewFieldSpec(accessconstrainthistory.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ActorKindCleared() {
		_spec.ClearField(accessconstrainthistory.FieldActorKind, field.TypeString)
	}
	if _u.mutation.ActorIDCleared() {
		_spec.ClearField(accessconstrainthistory.FieldActorID, field.TypeString)
	}
	if _u.mutation.CorrelationIDCleared() {
		_spec.ClearField(accessconstrainthistory.FieldCorrelationID, field.TypeString)
	}
	if _u.mutation.BatchOperationIDCleared() {
		_spec.ClearField(accessconstrainthistory.FieldBatchOperationID, field.TypeString)
	}
	if _u.mutation.BeforeRevisionCleared() {
		_spec.ClearField(accessconstrainthistory.FieldBeforeRevision, field.TypeInt64)
	}
	if _u.mutation.AfterRevisionCleared() {
		_spec.ClearField(accessconstrainthistory.FieldAfterRevision, field.TypeInt64)
	}
	if _u.mutation.ClassificationCleared() {
		_spec.ClearField(accessconstrainthistory.FieldClassification, field.TypeString)
	}
	if _u.mutation.PreviewIDCleared() {
		_spec.ClearField(accessconstrainthistory.FieldPreviewID, field.TypeString)
	}
	if _u.mutation.DraftHashCleared() {
		_spec.ClearField(accessconstrainthistory.FieldDraftHash, field.TypeString)
	}
	if _u.mutation.ImpactCountsJSONCleared() {
		_spec.ClearField(accessconstrainthistory.FieldImpactCountsJSON, field.TypeString)
	}
	if _u.mutation.ChangedFieldsJSONCleared() {
		_spec.ClearField(accessconstrainthistory.FieldChangedFieldsJSON, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accessconstrainthistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccessConstraintHistoryUpdateOne is the builder for updating a single AccessConstraintHistory entity.
type AccessConstraintHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccessConstraintHistoryMutation
}

// Mutation returns the AccessConstraintHistoryMutation object of the builder.
func (_u *AccessConstraintHistoryUpdateOne) Mutation() *AccessConstraintHistoryMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccessConstraintHistoryUpdate builder.
func (_u *AccessConstraintHistoryUpdateOne) Where(ps ...predicate.AccessConstraintHistory) *AccessConstraintHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccessConstraintHistoryUpdateOne) Select(field string, fields ...string) *AccessConstraintHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccessConstraintHistory entity.
func (_u *AccessConstraintHistoryUpdateOne) Save(ctx context.Context) (*AccessConstraintHistory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccessConstraintHistoryUpdateOne) SaveX(ctx context.Context) *AccessConstraintHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccessConstraintHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccessConstraintHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccessConstraintHistoryUpdateOne) check() error {
	if _u.mutation.ConstraintCleared() && len(_u.mutation.ConstraintIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccessConstraintHistory.constraint"`)
	}
	return nil
}

func (_u *AccessConstraintHistoryUpdateOne) sqlSave(ctx context.Context) (_node *AccessConstraintHistory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accessconstrainthistory.Table, accessconstrainthistory.Columns, sqlgraph.NewFieldSpec(accessconstrainthistory.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccessConstraintHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accessconstrainthistory.FieldID)
		for _, f := range fields {
			if !accessconstrainthistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accessconstrainthistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ActorKindCleared() {
		_spec.ClearField(accessconstrainthistory.FieldActorKind, field.TypeString)
	}
	if _u.mutation.ActorIDCleared() {
		_spec.ClearField(accessconstrainthistory.FieldActorID, field.TypeString)
	}
	if _u.mutation.CorrelationIDCleared() {
		_spec.ClearField(accessconstrainthistory.FieldCorrelationID, field.TypeString)
	}
	if _u.mutation.BatchOperationIDCleared() {
		_spec.ClearField(accessconstrainthistory.FieldBatchOperationID, field.TypeString)
	}
	if _u.mutation.BeforeRevisionCleared() {
		_spec.ClearField(accessconstrainthistory.FieldBeforeRevision, field.TypeInt64)
	}
	if _u.mutation.AfterRevisionCleared() {
		_spec.ClearField(accessconstrainthistory.FieldAfterRevision, field.TypeInt64)
	}
	if _u.mutation.ClassificationCleared() {
		_spec.ClearField(accessconstrainthistory.FieldClassification, field.TypeString)
	}
	if _u.mutation.PreviewIDCleared() {
		_spec.ClearField(accessconstrainthistory.FieldPreviewID, field.TypeString)
	}
	if _u.mutation.DraftHashCleared() {
		_spec.ClearField(accessconstrainthistory.FieldDraftHash, field.TypeString)
	}
	if _u.mutation.ImpactCountsJSONCleared() {
		_spec.ClearField(accessconstrainthistory.FieldImpactCountsJSON, field.TypeString)
	}
	if _u.mutation.ChangedFieldsJSONCleared() {
		_spec.ClearField(accessconstrainthistory.FieldChangedFieldsJSON, field.TypeString)
	}
	_node = &AccessConstraintHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accessconstrainthistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
