// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/projectprestarthook"
)

// ProjectPreStartHookDelete is the builder for deleting a ProjectPreStartHook entity.
type ProjectPreStartHookDelete struct {
	config
	hooks    []Hook
	mutation *ProjectPreStartHookMutation
}

// Where appends a list predicates to the ProjectPreStartHookDelete builder.
func (_d *ProjectPreStartHookDelete) Where(ps ...predicate.ProjectPreStartHook) *ProjectPreStartHookDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ProjectPreStartHookDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProjectPreStartHookDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ProjectPreStartHookDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(projectprestarthook.Table, sqlgraph.NewFieldSpec(projectprestarthook.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ProjectPreStartHookDeleteOne is the builder for deleting a single ProjectPreStartHook entity.
type ProjectPreStartHookDeleteOne struct {
	_d *ProjectPreStartHookDelete
}

// Where appends a list predicates to the ProjectPreStartHookDelete builder.
func (_d *ProjectPreStartHookDeleteOne) Where(ps ...predicate.ProjectPreStartHook) *ProjectPreStartHookDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ProjectPreStartHookDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{projectprestarthook.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProjectPreStartHookDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
