// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/userterminalworkspace"
)

// UserTerminalWorkspaceDelete is the builder for deleting a UserTerminalWorkspace entity.
type UserTerminalWorkspaceDelete struct {
	config
	hooks    []Hook
	mutation *UserTerminalWorkspaceMutation
}

// Where appends a list predicates to the UserTerminalWorkspaceDelete builder.
func (_d *UserTerminalWorkspaceDelete) Where(ps ...predicate.UserTerminalWorkspace) *UserTerminalWorkspaceDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserTerminalWorkspaceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserTerminalWorkspaceDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserTerminalWorkspaceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userterminalworkspace.Table, sqlgraph.NewFieldSpec(userterminalworkspace.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserTerminalWorkspaceDeleteOne is the builder for deleting a single UserTerminalWorkspace entity.
type UserTerminalWorkspaceDeleteOne struct {
	_d *UserTerminalWorkspaceDelete
}

// Where appends a list predicates to the UserTerminalWorkspaceDelete builder.
func (_d *UserTerminalWorkspaceDeleteOne) Where(ps ...predicate.UserTerminalWorkspace) *UserTerminalWorkspaceDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserTerminalWorkspaceDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userterminalworkspace.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserTerminalWorkspaceDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
