// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/userterminalworkspace"
)

// UserTerminalWorkspaceUpdate is the builder for updating UserTerminalWorkspace entities.
type UserTerminalWorkspaceUpdate struct {
	config
	hooks    []Hook
	mutation *UserTerminalWorkspaceMutation
}

// Where appends a list predicates to the UserTerminalWorkspaceUpdate builder.
func (_u *UserTerminalWorkspaceUpdate) Where(ps ...predicate.UserTerminalWorkspace) *UserTerminalWorkspaceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAgentIds sets the "agent_ids" field.
func (_u *UserTerminalWorkspaceUpdate) SetAgentIds(v []string) *UserTerminalWorkspaceUpdate {
	_u.mutation.SetAgentIds(v)
	return _u
}

// AppendAgentIds appends value to the "agent_ids" field.
func (_u *UserTerminalWorkspaceUpdate) AppendAgentIds(v []string) *UserTerminalWorkspaceUpdate {
	_u.mutation.AppendAgentIds(v)
	return _u
}

// SetFrontmostAgentID sets the "frontmost_agent_id" field.
func (_u *UserTerminalWorkspaceUpdate) SetFrontmostAgentID(v string) *UserTerminalWorkspaceUpdate {
	_u.mutation.SetFrontmostAgentID(v)
	return _u
}

// SetNillableFrontmostAgentID sets the "frontmost_agent_id" field if the given value is not nil.
func (_u *UserTerminalWorkspaceUpdate) SetNillableFrontmostAgentID(v *string) *UserTerminalWorkspaceUpdate {
	if v != nil {
		_u.SetFrontmostAgentID(*v)
	}
	return _u
}

// ClearFrontmostAgentID clears the value of the "frontmost_agent_id" field.
func (_u *UserTerminalWorkspaceUpdate) ClearFrontmostAgentID() *UserTerminalWorkspaceUpdate {
	_u.mutation.ClearFrontmostAgentID()
	return _u
}

// SetSchemaVersion sets the "schema_version" field.
func (_u *UserTerminalWorkspaceUpdate) SetSchemaVersion(v int) *UserTerminalWorkspaceUpdate {
	_u.mutation.ResetSchemaVersion()
	_u.mutation.SetSchemaVersion(v)
	return _u
}

// SetNillableSchemaVersion sets the "schema_version" field if the given value is not nil.
func (_u *UserTerminalWorkspaceUpdate) SetNillableSchemaVersion(v *int) *UserTerminalWorkspaceUpdate {
	if v != nil {
		_u.SetSchemaVersion(*v)
	}
	return _u
}

// AddSchemaVersion adds value to the "schema_version" field.
func (_u *UserTerminalWorkspaceUpdate) AddSchemaVersion(v int) *UserTerminalWorkspaceUpdate {
	_u.mutation.AddSchemaVersion(v)
	return _u
}

// SetRevision sets the "revision" field.
func (_u *UserTerminalWorkspaceUpdate) SetRevision(v int64) *UserTerminalWorkspaceUpdate {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *UserTerminalWorkspaceUpdate) SetNillableRevision(v *int64) *UserTerminalWorkspaceUpdate {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *UserTerminalWorkspaceUpdate) AddRevision(v int64) *UserTerminalWorkspaceUpdate {
	_u.mutation.AddRevision(v)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *UserTerminalWorkspaceUpdate) SetUpdateTime(v time.Time) *UserTerminalWorkspaceUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// Mutation returns the UserTerminalWorkspaceMutation object of the builder.
func (_u *UserTerminalWorkspaceUpdate) Mutation() *UserTerminalWorkspaceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserTerminalWorkspaceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserTerminalWorkspaceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserTerminalWorkspaceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserTerminalWorkspaceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserTerminalWorkspaceUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := userterminalworkspace.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserTerminalWorkspaceUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserTerminalWorkspace.user"`)
	}
	return nil
}

func (_u *UserTerminalWorkspaceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userterminalworkspace.Table, userterminalworkspace.Columns, sqlgraph.NewFieldSpec(userterminalworkspace.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AgentIds(); ok {
		_spec.SetField(userterminalworkspace.FieldAgentIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAgentIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, userterminalworkspace.FieldAgentIds, value)
		})
	}
	if value, ok := _u.mutation.FrontmostAgentID(); ok {
		_spec.SetField(userterminalworkspace.FieldFrontmostAgentID, field.TypeString, value)
	}
	if _u.mutation.FrontmostAgentIDCleared() {
		_spec.ClearField(userterminalworkspace.FieldFrontmostAgentID, field.TypeString)
	}
	if value, ok := _u.mutation.SchemaVersion(); ok {
		_spec.SetField(userterminalworkspace.FieldSchemaVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSchemaVersion(); ok {
		_spec.AddField(userterminalworkspace.FieldSchemaVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(userterminalworkspace.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(userterminalworkspace.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(userterminalworkspace.FieldUpdateTime, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userterminalworkspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserTerminalWorkspaceUpdateOne is the builder for updating a single UserTerminalWorkspace entity.
type UserTerminalWorkspaceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserTerminalWorkspaceMutation
}

// SetAgentIds sets the "agent_ids" field.
func (_u *UserTerminalWorkspaceUpdateOne) SetAgentIds(v []string) *UserTerminalWorkspaceUpdateOne {
	_u.mutation.SetAgentIds(v)
	return _u
}

// AppendAgentIds appends value to the "agent_ids" field.
func (_u *UserTerminalWorkspaceUpdateOne) AppendAgentIds(v []string) *UserTerminalWorkspaceUpdateOne {
	_u.mutation.AppendAgentIds(v)
	return _u
}

// SetFrontmostAgentID sets the "frontmost_agent_id" field.
func (_u *UserTerminalWorkspaceUpdateOne) SetFrontmostAgentID(v string) *UserTerminalWorkspaceUpdateOne {
	_u.mutation.SetFrontmostAgentID(v)
	return _u
}

// SetNillableFrontmostAgentID sets the "frontmost_agent_id" field if the given value is not nil.
func (_u *UserTerminalWorkspaceUpdateOne) SetNillableFrontmostAgentID(v *string) *UserTerminalWorkspaceUpdateOne {
	if v != nil {
		_u.SetFrontmostAgentID(*v)
	}
	return _u
}

// ClearFrontmostAgentID clears the value of the "frontmost_agent_id" field.
func (_u *UserTerminalWorkspaceUpdateOne) ClearFrontmostAgentID() *UserTerminalWorkspaceUpdateOne {
	_u.mutation.ClearFrontmostAgentID()
	return _u
}

// SetSchemaVersion sets the "schema_version" field.
func (_u *UserTerminalWorkspaceUpdateOne) SetSchemaVersion(v int) *UserTerminalWorkspaceUpdateOne {
	_u.mutation.ResetSchemaVersion()
	_u.mutation.SetSchemaVersion(v)
	return _u
}

// SetNillableSchemaVersion sets the "schema_version" field if the given value is not nil.
func (_u *UserTerminalWorkspaceUpdateOne) SetNillableSchemaVersion(v *int) *UserTerminalWorkspaceUpdateOne {
	if v != nil {
		_u.SetSchemaVersion(*v)
	}
	return _u
}

// AddSchemaVersion adds value to the "schema_version" field.
func (_u *UserTerminalWorkspaceUpdateOne) AddSchemaVersion(v int) *UserTerminalWorkspaceUpdateOne {
	_u.mutation.AddSchemaVersion(v)
	return _u
}

// SetRevision sets the "revision" field.
func (_u *UserTerminalWorkspaceUpdateOne) SetRevision(v int64) *UserTerminalWorkspaceUpdateOne {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *UserTerminalWorkspaceUpdateOne) SetNillableRevision(v *int64) *UserTerminalWorkspaceUpdateOne {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *UserTerminalWorkspaceUpdateOne) AddRevision(v int64) *UserTerminalWorkspaceUpdateOne {
	_u.mutation.AddRevision(v)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *UserTerminalWorkspaceUpdateOne) SetUpdateTime(v time.Time) *UserTerminalWorkspaceUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// Mutation returns the UserTerminalWorkspaceMutation object of the builder.
func (_u *UserTerminalWorkspaceUpdateOne) Mutation() *UserTerminalWorkspaceMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserTerminalWorkspaceUpdate builder.
func (_u *UserTerminalWorkspaceUpdateOne) Where(ps ...predicate.UserTerminalWorkspace) *UserTerminalWorkspaceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserTerminalWorkspaceUpdateOne) Select(field string, fields ...string) *UserTerminalWorkspaceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserTerminalWorkspace entity.
func (_u *UserTerminalWorkspaceUpdateOne) Save(ctx context.Context) (*UserTerminalWorkspace, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserTerminalWorkspaceUpdateOne) SaveX(ctx context.Context) *UserTerminalWorkspace {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserTerminalWorkspaceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserTerminalWorkspaceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserTerminalWorkspaceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := userterminalworkspace.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserTerminalWorkspaceUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserTerminalWorkspace.user"`)
	}
	return nil
}

func (_u *UserTerminalWorkspaceUpdateOne) sqlSave(ctx context.Context) (_node *UserTerminalWorkspace, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userterminalworkspace.Table, userterminalworkspace.Columns, sqlgraph.NewFieldSpec(userterminalworkspace.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserTerminalWorkspace.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userterminalworkspace.FieldID)
		for _, f := range fields {
			if !userterminalworkspace.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userterminalworkspace.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AgentIds(); ok {
		_spec.SetField(userterminalworkspace.FieldAgentIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAgentIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, userterminalworkspace.FieldAgentIds, value)
		})
	}
	if value, ok := _u.mutation.FrontmostAgentID(); ok {
		_spec.SetField(userterminalworkspace.FieldFrontmostAgentID, field.TypeString, value)
	}
	if _u.mutation.FrontmostAgentIDCleared() {
		_spec.ClearField(userterminalworkspace.FieldFrontmostAgentID, field.TypeString)
	}
	if value, ok := _u.mutation.SchemaVersion(); ok {
		_spec.SetField(userterminalworkspace.FieldSchemaVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSchemaVersion(); ok {
		_spec.AddField(userterminalworkspace.FieldSchemaVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(userterminalworkspace.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(userterminalworkspace.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(userterminalworkspace.FieldUpdateTime, field.TypeTime, value)
	}
	_node = &UserTerminalWorkspace{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userterminalworkspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
