// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/user"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/userterminalworkspace"
	"github.com/google/uuid"
)

// UserTerminalWorkspace is the model entity for the UserTerminalWorkspace schema.
type UserTerminalWorkspace struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// Ordered, lowercase canonical agent UUIDs; max 32; unique within the list
	AgentIds []string `json:"agent_ids,omitempty"`
	// Must be a member of agent_ids when set
	FrontmostAgentID *string `json:"frontmost_agent_id,omitempty"`
	// SchemaVersion holds the value of the "schema_version" field.
	SchemaVersion int `json:"schema_version,omitempty"`
	// Incremented on every write; informational (last-writer-wins)
	Revision int64 `json:"revision,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserTerminalWorkspaceQuery when eager-loading is set.
	Edges        UserTerminalWorkspaceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserTerminalWorkspaceEdges holds the relations/edges for other nodes in the graph.
type UserTerminalWorkspaceEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserTerminalWorkspaceEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserTerminalWorkspace) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userterminalworkspace.FieldAgentIds:
			values[i] = new([]byte)
		case userterminalworkspace.FieldSchemaVersion, userterminalworkspace.FieldRevision:
			values[i] = new(sql.NullInt64)
		case userterminalworkspace.FieldFrontmostAgentID:
			values[i] = new(sql.NullString)
		case userterminalworkspace.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case userterminalworkspace.FieldID, userterminalworkspace.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserTerminalWorkspace fields.
func (_m *UserTerminalWorkspace) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userterminalworkspace.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case userterminalworkspace.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case userterminalworkspace.FieldAgentIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field agent_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AgentIds); err != nil {
					return fmt.Errorf("unmarshal field agent_ids: %w", err)
				}
			}
		case userterminalworkspace.FieldFrontmostAgentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field frontmost_agent_id", values[i])
			} else if value.Valid {
				_m.FrontmostAgentID = new(string)
				*_m.FrontmostAgentID = value.String
			}
		case userterminalworkspace.FieldSchemaVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field schema_version", values[i])
			} else if value.Valid {
				_m.SchemaVersion = int(value.Int64)
			}
		case userterminalworkspace.FieldRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field revision", values[i])
			} else if value.Valid {
				_m.Revision = value.Int64
			}
		case userterminalworkspace.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserTerminalWorkspace.
// This includes values selected through modifiers, order, etc.
func (_m *UserTerminalWorkspace) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserTerminalWorkspace entity.
func (_m *UserTerminalWorkspace) QueryUser() *UserQuery {
	return NewUserTerminalWorkspaceClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserTerminalWorkspace.
// Note that you need to call UserTerminalWorkspace.Unwrap() before calling this method if this UserTerminalWorkspace
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserTerminalWorkspace) Update() *UserTerminalWorkspaceUpdateOne {
	return NewUserTerminalWorkspaceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserTerminalWorkspace entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserTerminalWorkspace) Unwrap() *UserTerminalWorkspace {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserTerminalWorkspace is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserTerminalWorkspace) String() string {
	var builder strings.Builder
	builder.WriteString("UserTerminalWorkspace(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("agent_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.AgentIds))
	builder.WriteString(", ")
	if v := _m.FrontmostAgentID; v != nil {
		builder.WriteString("frontmost_agent_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("schema_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.SchemaVersion))
	builder.WriteString(", ")
	builder.WriteString("revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.Revision))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserTerminalWorkspaces is a parsable slice of UserTerminalWorkspace.
type UserTerminalWorkspaces []*UserTerminalWorkspace
