// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/user"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/userterminalworkspace"
	"github.com/google/uuid"
)

// UserTerminalWorkspaceCreate is the builder for creating a UserTerminalWorkspace entity.
type UserTerminalWorkspaceCreate struct {
	config
	mutation *UserTerminalWorkspaceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserTerminalWorkspaceCreate) SetUserID(v uuid.UUID) *UserTerminalWorkspaceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAgentIds sets the "agent_ids" field.
func (_c *UserTerminalWorkspaceCreate) SetAgentIds(v []string) *UserTerminalWorkspaceCreate {
	_c.mutation.SetAgentIds(v)
	return _c
}

// SetFrontmostAgentID sets the "frontmost_agent_id" field.
func (_c *UserTerminalWorkspaceCreate) SetFrontmostAgentID(v string) *UserTerminalWorkspaceCreate {
	_c.mutation.SetFrontmostAgentID(v)
	return _c
}

// SetNillableFrontmostAgentID sets the "frontmost_agent_id" field if the given value is not nil.
func (_c *UserTerminalWorkspaceCreate) SetNillableFrontmostAgentID(v *string) *UserTerminalWorkspaceCreate {
	if v != nil {
		_c.SetFrontmostAgentID(*v)
	}
	return _c
}

// SetSchemaVersion sets the "schema_version" field.
func (_c *UserTerminalWorkspaceCreate) SetSchemaVersion(v int) *UserTerminalWorkspaceCreate {
	_c.mutation.SetSchemaVersion(v)
	return _c
}

// SetNillableSchemaVersion sets the "schema_version" field if the given value is not nil.
func (_c *UserTerminalWorkspaceCreate) SetNillableSchemaVersion(v *int) *UserTerminalWorkspaceCreate {
	if v != nil {
		_c.SetSchemaVersion(*v)
	}
	return _c
}

// SetRevision sets the "revision" field.
func (_c *UserTerminalWorkspaceCreate) SetRevision(v int64) *UserTerminalWorkspaceCreate {
	_c.mutation.SetRevision(v)
	return _c
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_c *UserTerminalWorkspaceCreate) SetNillableRevision(v *int64) *UserTerminalWorkspaceCreate {
	if v != nil {
		_c.SetRevision(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *UserTerminalWorkspaceCreate) SetUpdateTime(v time.Time) *UserTerminalWorkspaceCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *UserTerminalWorkspaceCreate) SetNillableUpdateTime(v *time.Time) *UserTerminalWorkspaceCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserTerminalWorkspaceCreate) SetID(v uuid.UUID) *UserTerminalWorkspaceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UserTerminalWorkspaceCreate) SetNillableID(v *uuid.UUID) *UserTerminalWorkspaceCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserTerminalWorkspaceCreate) SetUser(v *User) *UserTerminalWorkspaceCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserTerminalWorkspaceMutation object of the builder.
func (_c *UserTerminalWorkspaceCreate) Mutation() *UserTerminalWorkspaceMutation {
	return _c.mutation
}

// Save creates the UserTerminalWorkspace in the database.
func (_c *UserTerminalWorkspaceCreate) Save(ctx context.Context) (*UserTerminalWorkspace, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserTerminalWorkspaceCreate) SaveX(ctx context.Context) *UserTerminalWorkspace {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserTerminalWorkspaceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserTerminalWorkspaceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserTerminalWorkspaceCreate) defaults() {
	if _, ok := _c.mutation.SchemaVersion(); !ok {
		v := userterminalworkspace.DefaultSchemaVersion
		_c.mutation.SetSchemaVersion(v)
	}
	if _, ok := _c.mutation.Revision(); !ok {
		v := userterminalworkspace.DefaultRevision
		_c.mutation.SetRevision(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := userterminalworkspace.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := userterminalworkspace.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserTerminalWorkspaceCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserTerminalWorkspace.user_id"`)}
	}
	if _, ok := _c.mutation.AgentIds(); !ok {
		return &ValidationError{Name: "agent_ids", err: errors.New(`ent: missing required field "UserTerminalWorkspace.agent_ids"`)}
	}
	if _, ok := _c.mutation.SchemaVersion(); !ok {
		return &ValidationError{Name: "schema_version", err: errors.New(`ent: missing required field "UserTerminalWorkspace.schema_version"`)}
	}
	if _, ok := _c.mutation.Revision(); !ok {
		return &ValidationError{Name: "revision", err: errors.New(`ent: missing required field "UserTerminalWorkspace.revision"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "UserTerminalWorkspace.update_time"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserTerminalWorkspace.user"`)}
	}
	return nil
}

func (_c *UserTerminalWorkspaceCreate) sqlSave(ctx context.Context) (*UserTerminalWorkspace, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserTerminalWorkspaceCreate) createSpec() (*UserTerminalWorkspace, *sqlgraph.CreateSpec) {
	var (
		_node = &UserTerminalWorkspace{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userterminalworkspace.Table, sqlgraph.NewFieldSpec(userterminalworkspace.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.AgentIds(); ok {
		_spec.SetField(userterminalworkspace.FieldAgentIds, field.TypeJSON, value)
		_node.AgentIds = value
	}
	if value, ok := _c.mutation.FrontmostAgentID(); ok {
		_spec.SetField(userterminalworkspace.FieldFrontmostAgentID, field.TypeString, value)
		_node.FrontmostAgentID = &value
	}
	if value, ok := _c.mutation.SchemaVersion(); ok {
		_spec.SetField(userterminalworkspace.FieldSchemaVersion, field.TypeInt, value)
		_node.SchemaVersion = value
	}
	if value, ok := _c.mutation.Revision(); ok {
		_spec.SetField(userterminalworkspace.FieldRevision, field.TypeInt64, value)
		_node.Revision = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(userterminalworkspace.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userterminalworkspace.UserTable,
			Columns: []string{userterminalworkspace.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserTerminalWorkspace.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserTerminalWorkspaceUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserTerminalWorkspaceCreate) OnConflict(opts ...sql.ConflictOption) *UserTerminalWorkspaceUpsertOne {
	_c.conflict = opts
	return &UserTerminalWorkspaceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserTerminalWorkspace.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserTerminalWorkspaceCreate) OnConflictColumns(columns ...string) *UserTerminalWorkspaceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserTerminalWorkspaceUpsertOne{
		create: _c,
	}
}

type (
	// UserTerminalWorkspaceUpsertOne is the builder for "upsert"-ing
	//  one UserTerminalWorkspace node.
	UserTerminalWorkspaceUpsertOne struct {
		create *UserTerminalWorkspaceCreate
	}

	// UserTerminalWorkspaceUpsert is the "OnConflict" setter.
	UserTerminalWorkspaceUpsert struct {
		*sql.UpdateSet
	}
)

// SetAgentIds sets the "agent_ids" field.
func (u *UserTerminalWorkspaceUpsert) SetAgentIds(v []string) *UserTerminalWorkspaceUpsert {
	u.Set(userterminalworkspace.FieldAgentIds, v)
	return u
}

// UpdateAgentIds sets the "agent_ids" field to the value that was provided on create.
func (u *UserTerminalWorkspaceUpsert) UpdateAgentIds() *UserTerminalWorkspaceUpsert {
	u.SetExcluded(userterminalworkspace.FieldAgentIds)
	return u
}

// SetFrontmostAgentID sets the "frontmost_agent_id" field.
func (u *UserTerminalWorkspaceUpsert) SetFrontmostAgentID(v string) *UserTerminalWorkspaceUpsert {
	u.Set(userterminalworkspace.FieldFrontmostAgentID, v)
	return u
}

// UpdateFrontmostAgentID sets the "frontmost_agent_id" field to the value that was provided on create.
func (u *UserTerminalWorkspaceUpsert) UpdateFrontmostAgentID() *UserTerminalWorkspaceUpsert {
	u.SetExcluded(userterminalworkspace.FieldFrontmostAgentID)
	return u
}

// ClearFrontmostAgentID clears the value of the "frontmost_agent_id" field.
func (u *UserTerminalWorkspaceUpsert) ClearFrontmostAgentID() *UserTerminalWorkspaceUpsert {
	u.SetNull(userterminalworkspace.FieldFrontmostAgentID)
	return u
}

// SetSchemaVersion sets the "schema_version" field.
func (u *UserTerminalWorkspaceUpsert) SetSchemaVersion(v int) *UserTerminalWorkspaceUpsert {
	u.Set(userterminalworkspace.FieldSchemaVersion, v)
	return u
}

// UpdateSchemaVersion sets the "schema_version" field to the value that was provided on create.
func (u *UserTerminalWorkspaceUpsert) UpdateSchemaVersion() *UserTerminalWorkspaceUpsert {
	u.SetExcluded(userterminalworkspace.FieldSchemaVersion)
	return u
}

// AddSchemaVersion adds v to the "schema_version" field.
func (u *UserTerminalWorkspaceUpsert) AddSchemaVersion(v int) *UserTerminalWorkspaceUpsert {
	u.Add(userterminalworkspace.FieldSchemaVersion, v)
	return u
}

// SetRevision sets the "revision" field.
func (u *UserTerminalWorkspaceUpsert) SetRevision(v int64) *UserTerminalWorkspaceUpsert {
	u.Set(userterminalworkspace.FieldRevision, v)
	return u
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *UserTerminalWorkspaceUpsert) UpdateRevision() *UserTerminalWorkspaceUpsert {
	u.SetExcluded(userterminalworkspace.FieldRevision)
	return u
}

// AddRevision adds v to the "revision" field.
func (u *UserTerminalWorkspaceUpsert) AddRevision(v int64) *UserTerminalWorkspaceUpsert {
	u.Add(userterminalworkspace.FieldRevision, v)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *UserTerminalWorkspaceUpsert) SetUpdateTime(v time.Time) *UserTerminalWorkspaceUpsert {
	u.Set(userterminalworkspace.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *UserTerminalWorkspaceUpsert) UpdateUpdateTime() *UserTerminalWorkspaceUpsert {
	u.SetExcluded(userterminalworkspace.FieldUpdateTime)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.UserTerminalWorkspace.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(userterminalworkspace.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserTerminalWorkspaceUpsertOne) UpdateNewValues() *UserTerminalWorkspaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(userterminalworkspace.FieldID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(userterminalworkspace.FieldUserID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserTerminalWorkspace.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserTerminalWorkspaceUpsertOne) Ignore() *UserTerminalWorkspaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserTerminalWorkspaceUpsertOne) DoNothing() *UserTerminalWorkspaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserTerminalWorkspaceCreate.OnConflict
// documentation for more info.
func (u *UserTerminalWorkspaceUpsertOne) Update(set func(*UserTerminalWorkspaceUpsert)) *UserTerminalWorkspaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserTerminalWorkspaceUpsert{UpdateSet: update})
	}))
	return u
}

// SetAgentIds sets the "agent_ids" field.
func (u *UserTerminalWorkspaceUpsertOne) SetAgentIds(v []string) *UserTerminalWorkspaceUpsertOne {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.SetAgentIds(v)
	})
}

// UpdateAgentIds sets the "agent_ids" field to the value that was provided on create.
func (u *UserTerminalWorkspaceUpsertOne) UpdateAgentIds() *UserTerminalWorkspaceUpsertOne {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.UpdateAgentIds()
	})
}

// SetFrontmostAgentID sets the "frontmost_agent_id" field.
func (u *UserTerminalWorkspaceUpsertOne) SetFrontmostAgentID(v string) *UserTerminalWorkspaceUpsertOne {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.SetFrontmostAgentID(v)
	})
}

// UpdateFrontmostAgentID sets the "frontmost_agent_id" field to the value that was provided on create.
func (u *UserTerminalWorkspaceUpsertOne) UpdateFrontmostAgentID() *UserTerminalWorkspaceUpsertOne {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.UpdateFrontmostAgentID()
	})
}

// ClearFrontmostAgentID clears the value of the "frontmost_agent_id" field.
func (u *UserTerminalWorkspaceUpsertOne) ClearFrontmostAgentID() *UserTerminalWorkspaceUpsertOne {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.ClearFrontmostAgentID()
	})
}

// SetSchemaVersion sets the "schema_version" field.
func (u *UserTerminalWorkspaceUpsertOne) SetSchemaVersion(v int) *UserTerminalWorkspaceUpsertOne {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.SetSchemaVersion(v)
	})
}

// AddSchemaVersion adds v to the "schema_version" field.
func (u *UserTerminalWorkspaceUpsertOne) AddSchemaVersion(v int) *UserTerminalWorkspaceUpsertOne {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.AddSchemaVersion(v)
	})
}

// UpdateSchemaVersion sets the "schema_version" field to the value that was provided on create.
func (u *UserTerminalWorkspaceUpsertOne) UpdateSchemaVersion() *UserTerminalWorkspaceUpsertOne {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.UpdateSchemaVersion()
	})
}

// SetRevision sets the "revision" field.
func (u *UserTerminalWorkspaceUpsertOne) SetRevision(v int64) *UserTerminalWorkspaceUpsertOne {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.SetRevision(v)
	})
}

// AddRevision adds v to the "revision" field.
func (u *UserTerminalWorkspaceUpsertOne) AddRevision(v int64) *UserTerminalWorkspaceUpsertOne {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.AddRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *UserTerminalWorkspaceUpsertOne) UpdateRevision() *UserTerminalWorkspaceUpsertOne {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.UpdateRevision()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *UserTerminalWorkspaceUpsertOne) SetUpdateTime(v time.Time) *UserTerminalWorkspaceUpsertOne {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *UserTerminalWorkspaceUpsertOne) UpdateUpdateTime() *UserTerminalWorkspaceUpsertOne {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.UpdateUpdateTime()
	})
}

// Exec executes the query.
func (u *UserTerminalWorkspaceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserTerminalWorkspaceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserTerminalWorkspaceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserTerminalWorkspaceUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: UserTerminalWorkspaceUpsertOne.ID is not supported by MySQL driver. Use UserTerminalWorkspaceUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserTerminalWorkspaceUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserTerminalWorkspaceCreateBulk is the builder for creating many UserTerminalWorkspace entities in bulk.
type UserTerminalWorkspaceCreateBulk struct {
	config
	err      error
	builders []*UserTerminalWorkspaceCreate
	conflict []sql.ConflictOption
}

// Save creates the UserTerminalWorkspace entities in the database.
func (_c *UserTerminalWorkspaceCreateBulk) Save(ctx context.Context) ([]*UserTerminalWorkspace, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserTerminalWorkspace, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserTerminalWorkspaceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserTerminalWorkspaceCreateBulk) SaveX(ctx context.Context) []*UserTerminalWorkspace {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserTerminalWorkspaceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserTerminalWorkspaceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserTerminalWorkspace.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserTerminalWorkspaceUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserTerminalWorkspaceCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserTerminalWorkspaceUpsertBulk {
	_c.conflict = opts
	return &UserTerminalWorkspaceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserTerminalWorkspace.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserTerminalWorkspaceCreateBulk) OnConflictColumns(columns ...string) *UserTerminalWorkspaceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserTerminalWorkspaceUpsertBulk{
		create: _c,
	}
}

// UserTerminalWorkspaceUpsertBulk is the builder for "upsert"-ing
// a bulk of UserTerminalWorkspace nodes.
type UserTerminalWorkspaceUpsertBulk struct {
	create *UserTerminalWorkspaceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserTerminalWorkspace.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(userterminalworkspace.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserTerminalWorkspaceUpsertBulk) UpdateNewValues() *UserTerminalWorkspaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(userterminalworkspace.FieldID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(userterminalworkspace.FieldUserID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserTerminalWorkspace.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserTerminalWorkspaceUpsertBulk) Ignore() *UserTerminalWorkspaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserTerminalWorkspaceUpsertBulk) DoNothing() *UserTerminalWorkspaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserTerminalWorkspaceCreateBulk.OnConflict
// documentation for more info.
func (u *UserTerminalWorkspaceUpsertBulk) Update(set func(*UserTerminalWorkspaceUpsert)) *UserTerminalWorkspaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserTerminalWorkspaceUpsert{UpdateSet: update})
	}))
	return u
}

// SetAgentIds sets the "agent_ids" field.
func (u *UserTerminalWorkspaceUpsertBulk) SetAgentIds(v []string) *UserTerminalWorkspaceUpsertBulk {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.SetAgentIds(v)
	})
}

// UpdateAgentIds sets the "agent_ids" field to the value that was provided on create.
func (u *UserTerminalWorkspaceUpsertBulk) UpdateAgentIds() *UserTerminalWorkspaceUpsertBulk {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.UpdateAgentIds()
	})
}

// SetFrontmostAgentID sets the "frontmost_agent_id" field.
func (u *UserTerminalWorkspaceUpsertBulk) SetFrontmostAgentID(v string) *UserTerminalWorkspaceUpsertBulk {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.SetFrontmostAgentID(v)
	})
}

// UpdateFrontmostAgentID sets the "frontmost_agent_id" field to the value that was provided on create.
func (u *UserTerminalWorkspaceUpsertBulk) UpdateFrontmostAgentID() *UserTerminalWorkspaceUpsertBulk {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.UpdateFrontmostAgentID()
	})
}

// ClearFrontmostAgentID clears the value of the "frontmost_agent_id" field.
func (u *UserTerminalWorkspaceUpsertBulk) ClearFrontmostAgentID() *UserTerminalWorkspaceUpsertBulk {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.ClearFrontmostAgentID()
	})
}

// SetSchemaVersion sets the "schema_version" field.
func (u *UserTerminalWorkspaceUpsertBulk) SetSchemaVersion(v int) *UserTerminalWorkspaceUpsertBulk {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.SetSchemaVersion(v)
	})
}

// AddSchemaVersion adds v to the "schema_version" field.
func (u *UserTerminalWorkspaceUpsertBulk) AddSchemaVersion(v int) *UserTerminalWorkspaceUpsertBulk {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.AddSchemaVersion(v)
	})
}

// UpdateSchemaVersion sets the "schema_version" field to the value that was provided on create.
func (u *UserTerminalWorkspaceUpsertBulk) UpdateSchemaVersion() *UserTerminalWorkspaceUpsertBulk {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.UpdateSchemaVersion()
	})
}

// SetRevision sets the "revision" field.
func (u *UserTerminalWorkspaceUpsertBulk) SetRevision(v int64) *UserTerminalWorkspaceUpsertBulk {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.SetRevision(v)
	})
}

// AddRevision adds v to the "revision" field.
func (u *UserTerminalWorkspaceUpsertBulk) AddRevision(v int64) *UserTerminalWorkspaceUpsertBulk {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.AddRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *UserTerminalWorkspaceUpsertBulk) UpdateRevision() *UserTerminalWorkspaceUpsertBulk {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.UpdateRevision()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *UserTerminalWorkspaceUpsertBulk) SetUpdateTime(v time.Time) *UserTerminalWorkspaceUpsertBulk {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *UserTerminalWorkspaceUpsertBulk) UpdateUpdateTime() *UserTerminalWorkspaceUpsertBulk {
	return u.Update(func(s *UserTerminalWorkspaceUpsert) {
		s.UpdateUpdateTime()
	})
}

// Exec executes the query.
func (u *UserTerminalWorkspaceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserTerminalWorkspaceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserTerminalWorkspaceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserTerminalWorkspaceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
