// Code generated by ent, DO NOT EDIT.

package userterminalworkspace

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the userterminalworkspace type in the database.
	Label = "user_terminal_workspace"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAgentIds holds the string denoting the agent_ids field in the database.
	FieldAgentIds = "agent_ids"
	// FieldFrontmostAgentID holds the string denoting the frontmost_agent_id field in the database.
	FieldFrontmostAgentID = "frontmost_agent_id"
	// FieldSchemaVersion holds the string denoting the schema_version field in the database.
	FieldSchemaVersion = "schema_version"
	// FieldRevision holds the string denoting the revision field in the database.
	FieldRevision = "revision"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the userterminalworkspace in the database.
	Table = "user_terminal_workspaces"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_terminal_workspaces"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for userterminalworkspace fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldAgentIds,
	FieldFrontmostAgentID,
	FieldSchemaVersion,
	FieldRevision,
	FieldUpdateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSchemaVersion holds the default value on creation for the "schema_version" field.
	DefaultSchemaVersion int
	// DefaultRevision holds the default value on creation for the "revision" field.
	DefaultRevision int64
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the UserTerminalWorkspace queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByFrontmostAgentID orders the results by the frontmost_agent_id field.
func ByFrontmostAgentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrontmostAgentID, opts...).ToFunc()
}

// BySchemaVersion orders the results by the schema_version field.
func BySchemaVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSchemaVersion, opts...).ToFunc()
}

// ByRevision orders the results by the revision field.
func ByRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevision, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
	)
}
