// Code generated by ent, DO NOT EDIT.

package userterminalworkspace

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldEQ(FieldUserID, v))
}

// FrontmostAgentID applies equality check predicate on the "frontmost_agent_id" field. It's identical to FrontmostAgentIDEQ.
func FrontmostAgentID(v string) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldEQ(FieldFrontmostAgentID, v))
}

// SchemaVersion applies equality check predicate on the "schema_version" field. It's identical to SchemaVersionEQ.
func SchemaVersion(v int) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldEQ(FieldSchemaVersion, v))
}

// Revision applies equality check predicate on the "revision" field. It's identical to RevisionEQ.
func Revision(v int64) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldEQ(FieldRevision, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldEQ(FieldUpdateTime, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldNotIn(FieldUserID, vs...))
}

// FrontmostAgentIDEQ applies the EQ predicate on the "frontmost_agent_id" field.
func FrontmostAgentIDEQ(v string) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldEQ(FieldFrontmostAgentID, v))
}

// FrontmostAgentIDNEQ applies the NEQ predicate on the "frontmost_agent_id" field.
func FrontmostAgentIDNEQ(v string) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldNEQ(FieldFrontmostAgentID, v))
}

// FrontmostAgentIDIn applies the In predicate on the "frontmost_agent_id" field.
func FrontmostAgentIDIn(vs ...string) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldIn(FieldFrontmostAgentID, vs...))
}

// FrontmostAgentIDNotIn applies the NotIn predicate on the "frontmost_agent_id" field.
func FrontmostAgentIDNotIn(vs ...string) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldNotIn(FieldFrontmostAgentID, vs...))
}

// FrontmostAgentIDGT applies the GT predicate on the "frontmost_agent_id" field.
func FrontmostAgentIDGT(v string) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldGT(FieldFrontmostAgentID, v))
}

// FrontmostAgentIDGTE applies the GTE predicate on the "frontmost_agent_id" field.
func FrontmostAgentIDGTE(v string) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldGTE(FieldFrontmostAgentID, v))
}

// FrontmostAgentIDLT applies the LT predicate on the "frontmost_agent_id" field.
func FrontmostAgentIDLT(v string) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldLT(FieldFrontmostAgentID, v))
}

// FrontmostAgentIDLTE applies the LTE predicate on the "frontmost_agent_id" field.
func FrontmostAgentIDLTE(v string) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldLTE(FieldFrontmostAgentID, v))
}

// FrontmostAgentIDContains applies the Contains predicate on the "frontmost_agent_id" field.
func FrontmostAgentIDContains(v string) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldContains(FieldFrontmostAgentID, v))
}

// FrontmostAgentIDHasPrefix applies the HasPrefix predicate on the "frontmost_agent_id" field.
func FrontmostAgentIDHasPrefix(v string) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldHasPrefix(FieldFrontmostAgentID, v))
}

// FrontmostAgentIDHasSuffix applies the HasSuffix predicate on the "frontmost_agent_id" field.
func FrontmostAgentIDHasSuffix(v string) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldHasSuffix(FieldFrontmostAgentID, v))
}

// FrontmostAgentIDIsNil applies the IsNil predicate on the "frontmost_agent_id" field.
func FrontmostAgentIDIsNil() predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldIsNull(FieldFrontmostAgentID))
}

// FrontmostAgentIDNotNil applies the NotNil predicate on the "frontmost_agent_id" field.
func FrontmostAgentIDNotNil() predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldNotNull(FieldFrontmostAgentID))
}

// FrontmostAgentIDEqualFold applies the EqualFold predicate on the "frontmost_agent_id" field.
func FrontmostAgentIDEqualFold(v string) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldEqualFold(FieldFrontmostAgentID, v))
}

// FrontmostAgentIDContainsFold applies the ContainsFold predicate on the "frontmost_agent_id" field.
func FrontmostAgentIDContainsFold(v string) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldContainsFold(FieldFrontmostAgentID, v))
}

// SchemaVersionEQ applies the EQ predicate on the "schema_version" field.
func SchemaVersionEQ(v int) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldEQ(FieldSchemaVersion, v))
}

// SchemaVersionNEQ applies the NEQ predicate on the "schema_version" field.
func SchemaVersionNEQ(v int) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldNEQ(FieldSchemaVersion, v))
}

// SchemaVersionIn applies the In predicate on the "schema_version" field.
func SchemaVersionIn(vs ...int) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldIn(FieldSchemaVersion, vs...))
}

// SchemaVersionNotIn applies the NotIn predicate on the "schema_version" field.
func SchemaVersionNotIn(vs ...int) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldNotIn(FieldSchemaVersion, vs...))
}

// SchemaVersionGT applies the GT predicate on the "schema_version" field.
func SchemaVersionGT(v int) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldGT(FieldSchemaVersion, v))
}

// SchemaVersionGTE applies the GTE predicate on the "schema_version" field.
func SchemaVersionGTE(v int) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldGTE(FieldSchemaVersion, v))
}

// SchemaVersionLT applies the LT predicate on the "schema_version" field.
func SchemaVersionLT(v int) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldLT(FieldSchemaVersion, v))
}

// SchemaVersionLTE applies the LTE predicate on the "schema_version" field.
func SchemaVersionLTE(v int) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldLTE(FieldSchemaVersion, v))
}

// RevisionEQ applies the EQ predicate on the "revision" field.
func RevisionEQ(v int64) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldEQ(FieldRevision, v))
}

// RevisionNEQ applies the NEQ predicate on the "revision" field.
func RevisionNEQ(v int64) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldNEQ(FieldRevision, v))
}

// RevisionIn applies the In predicate on the "revision" field.
func RevisionIn(vs ...int64) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldIn(FieldRevision, vs...))
}

// RevisionNotIn applies the NotIn predicate on the "revision" field.
func RevisionNotIn(vs ...int64) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldNotIn(FieldRevision, vs...))
}

// RevisionGT applies the GT predicate on the "revision" field.
func RevisionGT(v int64) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldGT(FieldRevision, v))
}

// RevisionGTE applies the GTE predicate on the "revision" field.
func RevisionGTE(v int64) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldGTE(FieldRevision, v))
}

// RevisionLT applies the LT predicate on the "revision" field.
func RevisionLT(v int64) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldLT(FieldRevision, v))
}

// RevisionLTE applies the LTE predicate on the "revision" field.
func RevisionLTE(v int64) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldLTE(FieldRevision, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.FieldLTE(FieldUpdateTime, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserTerminalWorkspace) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserTerminalWorkspace) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserTerminalWorkspace) predicate.UserTerminalWorkspace {
	return predicate.UserTerminalWorkspace(sql.NotPredicates(p))
}
